import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // ==========================================================================
  // IMAGE OPTIMIZATION - Critical for Core Web Vitals (LCP)
  // ==========================================================================
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: '**' },
    ],
    // Modern formats for better compression
    formats: ['image/avif', 'image/webp'],
    // Responsive breakpoints
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    // Minimize layout shift with blur placeholder
    minimumCacheTTL: 60 * 60 * 24 * 365, // 1 year
    // Quality optimization
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
  
  // ==========================================================================
  // CDN CACHING & COMPRESSION HEADERS
  // ==========================================================================
  headers: async () => {
    return [
      // Static images - aggressive caching (1 year)
      {
        source: '/:path*.{jpg,jpeg,png,gif,webp,avif,svg,ico}',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=31536000, immutable'
          },
          {
            key: 'Vary',
            value: 'Accept'
          },
        ],
      },
      // Fonts - aggressive caching with CORS
      {
        source: '/:path*.{woff,woff2,ttf,otf,eot}',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=31536000, immutable'
          },
          {
            key: 'Access-Control-Allow-Origin',
            value: '*'
          },
        ],
      },
      // JS and CSS bundles - immutable caching
      {
        source: '/_next/static/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=31536000, immutable'
          },
        ],
      },
      // HTML pages - short cache with stale-while-revalidate
      {
        source: '/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=60, s-maxage=120, stale-while-revalidate=600'
          },
          // Security headers
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff'
          },
          {
            key: 'X-Frame-Options',
            value: 'DENY'
          },
          {
            key: 'X-XSS-Protection',
            value: '1; mode=block'
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin'
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=()'
          },
        ],
      },
      // Sitemaps and feeds - moderate caching
      {
        source: '/:path*.xml',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400'
          },
          {
            key: 'Content-Type',
            value: 'application/xml; charset=utf-8'
          },
        ],
      },
    ];
  },
  
  // ==========================================================================
  // URL NORMALIZATION (SEO)
  // ==========================================================================
  trailingSlash: false,
  
  // ==========================================================================
  // REDIRECTS (301 Permanent Redirects for SEO)
  // ==========================================================================
  redirects: async () => {
    return [
      // Blog URL migration - old /blog/ paths to root
      {
        source: '/blog/sam-altman-visits-hedera-team',
        destination: '/sam-altman-visits-hedera-team',
        permanent: true, // 301 redirect
      },
      
      // Blitzy review URL consolidation
      {
        source: '/blitzy-ai-powered-autonomous-software-development-platform-developer-review-for-2025',
        destination: '/blitzy-ai-powered-autonomous-software-development',
        permanent: true, // 301 redirect
      },
      
      // ==========================================================================
      // SIDEMEN CONTENT MIGRATION - Moved from /sidemen to /youtube/sidemen
      // Date: February 7, 2026
      // ==========================================================================
      
      // Main Sidemen hub page
      {
        source: '/sidemen',
        destination: '/youtube/sidemen',
        permanent: true,
      },
      
      // Individual Sidemen member pages
      {
        source: '/sidemen/ksi',
        destination: '/youtube/sidemen/ksi',
        permanent: true,
      },
      {
        source: '/sidemen/miniminter',
        destination: '/youtube/sidemen/miniminter',
        permanent: true,
      },
      {
        source: '/sidemen/zerkaa',
        destination: '/youtube/sidemen/zerkaa',
        permanent: true,
      },
      {
        source: '/sidemen/tbjzl',
        destination: '/youtube/sidemen/tbjzl',
        permanent: true,
      },
      {
        source: '/sidemen/behzinga',
        destination: '/youtube/sidemen/behzinga',
        permanent: true,
      },
      {
        source: '/sidemen/vikkstar',
        destination: '/youtube/sidemen/vikkstar',
        permanent: true,
      },
      {
        source: '/sidemen/w2s',
        destination: '/youtube/sidemen/w2s',
        permanent: true,
      },
      
      // Wildcard catch-all for any other /sidemen/* paths
      {
        source: '/sidemen/:path*',
        destination: '/youtube/sidemen/:path*',
        permanent: true,
      },

      // ==========================================================================
      // CRYPTO CONTENT MIGRATION - /crypto hub restored, only wiki-style
      // definitions still redirect to /define/crypto/*
      // Date: April 2, 2026
      // ==========================================================================

      {
        source: '/crypto/tether',
        destination: '/define/crypto/tether',
        permanent: true,
      },
      {
        source: '/crypto/txc-stablecoin',
        destination: '/define/crypto/txc-stablecoin',
        permanent: true,
      },

      // ==========================================================================
      // CONTENT CONSOLIDATION — May 2026
      // 584 non-top-100 pages redirected to their nearest hub or /news
      // ==========================================================================
      { source: '/airlines/jetblue/jetblue-surveillance-pricing-lawsuit-personal-data-2026', destination: '/news', permanent: true },
      { source: '/amazon/news/amazon-1-hour-3-hour-delivery-us-launch-march-2026', destination: '/amazon', permanent: true },
      { source: '/amazon/news/amazon-acquires-fauna-robotics-sprout-humanoid', destination: '/amazon', permanent: true },
      { source: '/amazon/news/amazon-one-medical-glp1-hims-hers-price-war-2026', destination: '/amazon', permanent: true },
      { source: '/amazon/news/andy-jassy-2025-pay-2-1-million-30-percent-raise', destination: '/amazon', permanent: true },
      { source: '/amazon/news/andy-jassy-ai-will-reduce-headcount-many-roles-cnbc-february-2026', destination: '/amazon', permanent: true },
      { source: '/amazon/news/aws-uae-data-center-fire-iran-strikes-march-2026', destination: '/amazon', permanent: true },
      { source: '/apple/apple-iphone-18-delay-2027-foldable', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-50th-anniversary-apple-park-grand-finale-2026', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-ceo-transition-tim-cook-steps-down-john-ternus-2026', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-google-gemini-partnership', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-march-2026-products-macbook-iphone-17e-ipad-air-m5', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-post-iphone-gurman-6-secret-products-ambient-ai-2026', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-removes-anything-vibe-coding-app-store-2026', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-video-podcasts-youtube', destination: '/apple', permanent: true },
      { source: '/apple/news/california-based-act-antitrust-sb1074-2026', destination: '/apple', permanent: true },
      { source: '/apple/news/f1-apple-tv-espn-domenicali', destination: '/apple', permanent: true },
      { source: '/apple/news/mac-mini-houston-tx', destination: '/apple', permanent: true },
      { source: '/articlepage/test', destination: '/news', permanent: true },
      { source: '/artists/don-toliver/octane-review-features', destination: '/news', permanent: true },
      { source: '/artists', destination: '/news', permanent: true },
      { source: '/austin/michael-dell-750-million-ut-austin-ai-hospital-2026', destination: '/tech', permanent: true },
      { source: '/austin/waymo-city-council-bufords-ambulance-obstruction-2026', destination: '/tech', permanent: true },
      { source: '/bank-of-america', destination: '/news', permanent: true },
      { source: '/bio-hacking/bianca-dias-bbl-death-brazil-insurance-shift', destination: '/bio-hacking', permanent: true },
      { source: '/bio-hacking/eledon-pharmaceuticals-eldn-cd40l-tegoprubart-transplant-2026', destination: '/bio-hacking', permanent: true },
      { source: '/bio-hacking/news/oslo-patient-hiv-cure-ccr5-bone-marrow-transplant-2026', destination: '/bio-hacking', permanent: true },
      { source: '/bio-hacking/news/rockefeller-crispr-stem-cell-living-drug-factory-hiv-malaria-influenza', destination: '/bio-hacking', permanent: true },
      { source: '/bio-hacking/news/science-study-3000-genes-sex-differences-human-brain-decasien-2026', destination: '/bio-hacking', permanent: true },
      { source: '/bio-hacking/penn-study-unreported-glp-1-side-effects-reddit', destination: '/bio-hacking', permanent: true },
      { source: '/blackrock/blackrock-fidelity-bought-400m-bitcoin-golds-worst-weekly-drop', destination: '/crypto', permanent: true },
      { source: '/blackrock/news/blackrock-57-million-iqm-quantum-computers-us-listing-2026', destination: '/news', permanent: true },
      { source: '/blackrock/news/blackrock-600m-bitcoin-cold-storage-ibit-etf-settlement', destination: '/crypto', permanent: true },
      { source: '/blackrock', destination: '/news', permanent: true },
      { source: '/blitzy-ai-powered-autonomous-software-development', destination: '/tech', permanent: true },
      { source: '/blog', destination: '/news', permanent: true },
      { source: '/california/california-highway-expansion-2026-state-transportation-improvement-program', destination: '/california', permanent: true },
      { source: '/cars/2025-nissan-z-vs-toyota-gr-supra-comparison', destination: '/news', permanent: true },
      { source: '/cars/ferrari', destination: '/news', permanent: true },
      { source: '/cars/ford', destination: '/news', permanent: true },
      { source: '/cars/porsche/911-gt3-sc-sport-cabriolet-reveal-2026', destination: '/news', permanent: true },
      { source: '/cars/porsche', destination: '/news', permanent: true },
      { source: '/cars/tesla-semi-truckers-mass-production-nevada-2026', destination: '/news', permanent: true },
      { source: '/central-cee/all-roads-lead-home-march-28th-ep', destination: '/news', permanent: true },
      { source: '/claude/news/anthropic-claude-design-conversational-visual-canvas-canva-partnership', destination: '/tech', permanent: true },
      { source: '/claude/news/anthropic-claude-pro-plan-claude-code-access-2026', destination: '/tech', permanent: true },
      { source: '/claude/news/anthropic-coreweave-multiyear-data-center-deal', destination: '/tech', permanent: true },
      { source: '/claude/news/anthropic-government-id-verification-claude', destination: '/tech', permanent: true },
      { source: '/claude/news/anthropic-mythos-uk-banks-access-pip-white', destination: '/tech', permanent: true },
      { source: '/claude/news/anthropic-mythos-uk-banks-expansion', destination: '/tech', permanent: true },
      { source: '/claude/news/antrhopic-opus-3-retires', destination: '/tech', permanent: true },
      { source: '/claude/news/datatalks-course-wiped-by-claudecode', destination: '/tech', permanent: true },
      { source: '/claude/news/ecb-anthropic-claude-mythos-systemic-risk-inquiry', destination: '/tech', permanent: true },
      { source: '/claude/news/federal-agencies-replace-claude-gpt-41-trump-executive-directive', destination: '/tech', permanent: true },
      { source: '/claude/news/imf-georgieva-anthropic-mythos-financial-stability-warning', destination: '/tech', permanent: true },
      { source: '/claude/news/software-stocks-crater-anthropic-mythos-gatekeep', destination: '/tech', permanent: true },
      { source: '/claude/news/white-house-omb-federal-agencies-anthropic-mythos-access', destination: '/tech', permanent: true },
      { source: '/clothing/fabletics', destination: '/clothing', permanent: true },
      { source: '/clothing/gymshark/which-gymshark-leggings-are-best-for-lifting', destination: '/clothing/gymshark', permanent: true },
      { source: '/clothing/new-balance/energy-arc-fuelcell-supercomp', destination: '/clothing', permanent: true },
      { source: '/clothing/new-balance', destination: '/clothing', permanent: true },
      { source: '/clothing/skims/ceo', destination: '/clothing', permanent: true },
      { source: '/clothing/skims/creative-director', destination: '/clothing', permanent: true },
      { source: '/clothing/skims', destination: '/clothing', permanent: true },
      { source: '/clothing/vans', destination: '/clothing', permanent: true },
      { source: '/clothing/young-la', destination: '/clothing', permanent: true },
      { source: '/college/guides/non-degree-studies-at-university-of-texas-austin', destination: '/news', permanent: true },
      { source: '/copyright/elemental-atlus-royalties', destination: '/copyright', permanent: true },
      { source: '/copyright/meta/meta-child-safety-verdicts-new-mexico-los-angeles-march-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/meta/news/new-mexico-jury-meta-375m-consumer-protection-verdict-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/news/aoc-mlb-polymarket-gambling-warning', destination: '/copyright', permanent: true },
      { source: '/copyright/news/baltimore-xai-grok-sexual-deepfakes-lawsuit-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/news/circle-class-action-drift-protocol-285m-hack-solana', destination: '/copyright', permanent: true },
      { source: '/copyright/news/deere-99m-settlement-right-to-repair-digital-tools', destination: '/copyright', permanent: true },
      { source: '/copyright/news/detroit-first-city-oppose-prediction-markets-coinbase-lawsuit-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/news/kalshi-suspends-candidates-betting-own-races-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/news/letitia-james-sues-counter-strike', destination: '/copyright', permanent: true },
      { source: '/copyright/news/ninth-circuit-pauses-app-store-ruling-apple-supreme-court', destination: '/copyright', permanent: true },
      { source: '/copyright/news/trump-prediction-markets-cftc-van-dyke-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/nicole-daedone-sentenced-9-years-onetaste-forced-labor-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/sony/playstation-age-verification-psn-online-safety-laws-2026', destination: '/copyright', permanent: true },
      { source: '/crypto/bernstein-circle-coinbase-stablecoin-kings-ai-era', destination: '/crypto', permanent: true },
      { source: '/crypto/coinbase/clarity-act-stablecoin-yield-ban', destination: '/crypto', permanent: true },
      { source: '/crypto/coinbase-new-york-ath-ray-nct-strk-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/hbar/rba-cbdc-hashsphere-hedera-project-acacia', destination: '/crypto', permanent: true },
      { source: '/crypto/news/anchorage-digital-tron-institutional-custody-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/news/anchorage-usat-expands-to-celo-network', destination: '/crypto', permanent: true },
      { source: '/crypto/news/bip-361-quantum-bitcoin-legacy-sunset', destination: '/crypto', permanent: true },
      { source: '/crypto/news/bitcoin-whale-20m-binance-large-holder-selloffs', destination: '/crypto', permanent: true },
      { source: '/crypto/news/chainlink-anchorage-blockchain-leadership-fund-pac-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/news/coinbase-armstrong-network-states-everything-exchange', destination: '/crypto', permanent: true },
      { source: '/crypto/news/fed-cbdc-halted-stablecoins-digital-dollar-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/news/florida-hb175-stablecoin-law-payment-regulation', destination: '/crypto', permanent: true },
      { source: '/crypto/news/kucoin-cftc-settlement-us-bar-peken-global', destination: '/crypto', permanent: true },
      { source: '/crypto/news/ripple-convera-stablecoin-sandwich-b2b-payments', destination: '/crypto', permanent: true },
      { source: '/crypto/news/tether-fasset-gold-visa-card-xaut-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/news/tether-qvac-sdk-on-device-ai-cloud-monopoly', destination: '/crypto', permanent: true },
      { source: '/crypto/news/visa-usdc-solana-settlement-lead-bank-cross-river', destination: '/crypto', permanent: true },
      { source: '/crypto/trump/meme-coin-gala-whca-shooting-sanders-4b-kleptocracy-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/usdc/circle-mints-750m-on-solana-network', destination: '/crypto', permanent: true },
      { source: '/crypto/usdc/circle-unfreeze-wallets-zachxbt-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/usdc/news/circle-usdc-drift-hack-285m-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/usdc', destination: '/crypto', permanent: true },
      { source: '/crypto/warren-mrbeast-step-crypto-children', destination: '/crypto', permanent: true },
      { source: '/crypto/white-house-block-and-find-out-coinbase-clarity-act-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/xrp/80b-ledger-exploit-confirmed-by-ceo', destination: '/crypto', permanent: true },
      { source: '/crypto/xrp', destination: '/crypto', permanent: true },
      { source: '/cuba/news/cuban-border-guards-kill-four-florida-speedboat-cayo-falcones', destination: '/news', permanent: true },
      { source: '/define/agentic-ai', destination: '/tech', permanent: true },
      { source: '/define/bets-off-act', destination: '/news', permanent: true },
      { source: '/define/comet-ai-web-browser-vs-atlas-by-chatgpt', destination: '/comet-ai-web-browser-vs-atlas-by-chatgpt', permanent: true },
      { source: '/define/crypto/tether', destination: '/crypto', permanent: true },
      { source: '/define/crypto/txc-stablecoin', destination: '/crypto', permanent: true },
      { source: '/define/democrate/dhs-funding-shutdown-senate-democrats-counteroffer-march-2026', destination: '/news', permanent: true },
      { source: '/define/difference-between-http-and-rest-api-servers', destination: '/tech', permanent: true },
      { source: '/define/hedera-vs-solana-for-dapps', destination: '/crypto', permanent: true },
      { source: '/define/how-do-prediction-markets-work', destination: '/news', permanent: true },
      { source: '/define/largest-prediction-markets-united-states-2026', destination: '/news', permanent: true },
      { source: '/define/malware/axios-npm-hijacked-rat-malware', destination: '/tech', permanent: true },
      { source: '/define/malware/deepload-ai-obfuscation-clickfix-2026', destination: '/tech', permanent: true },
      { source: '/define/model-context-protocol', destination: '/tech', permanent: true },
      { source: '/define/most-important-stablecoins-world-2026', destination: '/crypto', permanent: true },
      { source: '/define/nestjs-vs-nextjs-express', destination: '/tech', permanent: true },
      { source: '/define/openai-hires-openclaw-creator-peter-steinberger-foundation', destination: '/open-ai', permanent: true },
      { source: '/define/prediction-market/:path*', destination: '/news', permanent: true },
      { source: '/define/proof-of-engagement-blockchain-vs-proof-of-authority', destination: '/crypto', permanent: true },
      { source: '/define/tariff', destination: '/news', permanent: true },
      { source: '/define/vibe-coding', destination: '/tech', permanent: true },
      { source: '/define/what-is-a-smart-contract', destination: '/crypto', permanent: true },
      { source: '/define/what-is-a-stablecoin', destination: '/crypto', permanent: true },
      { source: '/define/what-is-an-llm', destination: '/tech', permanent: true },
      { source: '/define/what-is-bitcoin-halving', destination: '/crypto', permanent: true },
      { source: '/define/what-is-defi', destination: '/crypto', permanent: true },
      { source: '/define/what-is-esports', destination: '/video-games', permanent: true },
      { source: '/disney/josh-damaro', destination: '/disney', permanent: true },
      { source: '/disney/news/:path*', destination: '/disney', permanent: true },
      { source: '/earth/news/:path*', destination: '/news', permanent: true },
      { source: '/earth/:path*', destination: '/news', permanent: true },
      { source: '/editorial-standards/authors', destination: '/editorial-standards', permanent: true },
      { source: '/elon-musk/boring-company/news/:path*', destination: '/elon-musk/boring-company', permanent: true },
      { source: '/elon-musk/news/:path*', destination: '/elon-musk', permanent: true },
      { source: '/elon-musk/spacex', destination: '/elon-musk', permanent: true },
      { source: '/elon-musk/spacex-xai-merger-1-75-trillion-ipo-orbital-ai-2026', destination: '/elon-musk', permanent: true },
      { source: '/elon-musk/sun-shading-the-billionaire-wants-ai-satellites-to-block-the-sun', destination: '/elon-musk', permanent: true },
      { source: '/entertainment/apple-tv/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/beastgames/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/beastgames', destination: '/entertainment', permanent: true },
      { source: '/entertainment/hbo-max/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/hbomax', destination: '/entertainment', permanent: true },
      { source: '/entertainment/hulu', destination: '/entertainment', permanent: true },
      { source: '/entertainment/james-cameron', destination: '/entertainment', permanent: true },
      { source: '/entertainment/marvel/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/movies/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/netflix', destination: '/entertainment', permanent: true },
      { source: '/entertainment/news/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/survivor', destination: '/entertainment', permanent: true },
      { source: '/equipment/:path*', destination: '/news', permanent: true },
      { source: '/events/ceraweek-2026', destination: '/news', permanent: true },
      { source: '/events/davos/:path*', destination: '/events/davos', permanent: true },
      { source: '/events/gdc-2026/:path*', destination: '/news', permanent: true },
      { source: '/events/gdc-2026', destination: '/news', permanent: true },
      { source: '/events/gtc-2026/:path*', destination: '/news', permanent: true },
      { source: '/events/gtc-2026', destination: '/news', permanent: true },
      { source: '/events/news/:path*', destination: '/news', permanent: true },
      { source: '/events/starbucks/:path*', destination: '/news', permanent: true },
      { source: '/events/sxsw', destination: '/news', permanent: true },
      { source: '/finance/:path*', destination: '/news', permanent: true },
      { source: '/finance', destination: '/news', permanent: true },
      { source: '/formula-1/:path*', destination: '/news', permanent: true },
      { source: '/get-help/:path*', destination: '/get-help', permanent: true },
      { source: '/github/news/:path*', destination: '/github', permanent: true },
      { source: '/google/agentic-vision/:path*', destination: '/google', permanent: true },
      { source: '/google/news/alphabet-:path*', destination: '/google', permanent: true },
      { source: '/google/news/anthropic-:path*', destination: '/google', permanent: true },
      { source: '/google/news/apple-gemini-siri-upgrade-march-2026', destination: '/google', permanent: true },
      { source: '/google/news/google-deepmind-:path*', destination: '/google', permanent: true },
      { source: '/google/news/kering-:path*', destination: '/google', permanent: true },
      { source: '/google/news/nvidia-google-:path*', destination: '/google', permanent: true },
      { source: '/google/waymo/ntsb-investigation-school-bus-violations', destination: '/google', permanent: true },
      { source: '/history', destination: '/news', permanent: true },
      { source: '/index', destination: '/news', permanent: true },
      { source: '/indonesia/:path*', destination: '/news', permanent: true },
      { source: '/influencer/abby-berner', destination: '/influencer', permanent: true },
      { source: '/influencer/alanforze/:path*', destination: '/influencer', permanent: true },
      { source: '/influencer/alix-earle', destination: '/influencer', permanent: true },
      { source: '/influencer/bryson-dechambeau/:path*', destination: '/influencer', permanent: true },
      { source: '/influencer/bryson-dechambeau', destination: '/influencer', permanent: true },
      { source: '/influencer/bufalika', destination: '/influencer', permanent: true },
      { source: '/influencer/charli-damelio', destination: '/influencer', permanent: true },
      { source: '/influencer/colleen-sheehan', destination: '/influencer', permanent: true },
      { source: '/influencer/emma-chamberlain', destination: '/influencer', permanent: true },
      { source: '/influencer/iman-gadzhi', destination: '/influencer', permanent: true },
      { source: '/influencer/leah-davies', destination: '/influencer', permanent: true },
      { source: '/influencer/lean-beef-patty', destination: '/influencer', permanent: true },
      { source: '/influencer/megan-marie', destination: '/influencer', permanent: true },
      { source: '/influencer/mika-lafuente', destination: '/influencer', permanent: true },
      { source: '/influencer/miranda-marie', destination: '/influencer', permanent: true },
      { source: '/influencer/mrbeast/:path*', destination: '/influencer', permanent: true },
      { source: '/influencer/mrbeast', destination: '/influencer', permanent: true },
      { source: '/influencer/mrbeast-launches-beast-games-season-2-casting', destination: '/influencer', permanent: true },
      { source: '/influencer/news/:path*', destination: '/influencer', permanent: true },
      { source: '/influencer/nick-shirley', destination: '/influencer', permanent: true },
      { source: '/influencer/of/mikaela-testa', destination: '/influencer', permanent: true },
      { source: '/influencer/pokimane', destination: '/influencer', permanent: true },
      { source: '/influencer/serge-gatari/:path*', destination: '/influencer', permanent: true },
      { source: '/influencer/sssniperwolf', destination: '/influencer', permanent: true },
      { source: '/influencer/tren-twins', destination: '/influencer', permanent: true },
      { source: '/influencer/valkyrae', destination: '/influencer', permanent: true },
      { source: '/influencer/yellz0', destination: '/influencer', permanent: true },
      { source: '/intel/news/:path*', destination: '/intel', permanent: true },
      { source: '/investigations/:path*', destination: '/news', permanent: true },
      { source: '/ironspring-ventures-startups-are-changing-construction-goodship-track3d-fleetpulse', destination: '/news', permanent: true },
      { source: '/jackarticle/test', destination: '/news', permanent: true },
      { source: '/lawsuit/:path*', destination: '/news', permanent: true },
      { source: '/meta/:path*', destination: '/news', permanent: true },
      { source: '/meta', destination: '/news', permanent: true },
      { source: '/microsoft/news/amazon-:path*', destination: '/microsoft', permanent: true },
      { source: '/microsoft/news/aws-:path*', destination: '/microsoft', permanent: true },
      { source: '/microsoft/news/eledon-:path*', destination: '/microsoft', permanent: true },
      { source: '/microsoft/news/how-to-:path*', destination: '/microsoft', permanent: true },
      { source: '/microsoft/news/microsoft-:path*', destination: '/microsoft', permanent: true },
      { source: '/microsoft/news/nadella-:path*', destination: '/microsoft', permanent: true },
      { source: '/microsoft/news/project-helix-:path*', destination: '/microsoft', permanent: true },
      { source: '/microsoft/news/xbox-co-creator-:path*', destination: '/microsoft', permanent: true },
      { source: '/microsoft/xbox/project-moorcroft-:path*', destination: '/microsoft', permanent: true },
      { source: '/microsoft/xbox', destination: '/microsoft', permanent: true },
      { source: '/missing-persons', destination: '/news', permanent: true },
      { source: '/mls/:path*', destination: '/news', permanent: true },
      { source: '/nasa/europa/:path*', destination: '/nasa', permanent: true },
      { source: '/nasa/news/esa-:path*', destination: '/nasa', permanent: true },
      { source: '/nasa/news/first-close-pair-:path*', destination: '/nasa', permanent: true },
      { source: '/netflix/news/:path*', destination: '/news', permanent: true },
      { source: '/neurophos-ai-hardware-startup', destination: '/news', permanent: true },
      { source: '/news/2025/:path*', destination: '/news', permanent: true },
      { source: '/news/ai', destination: '/news', permanent: true },
      { source: '/news/alibaba-ai-agent-mined-crypto-during-training', destination: '/news', permanent: true },
      { source: '/news/artemis-ii-launch-lunar-journey-april-2026', destination: '/news', permanent: true },
      { source: '/news/binance-:path*', destination: '/news', permanent: true },
      { source: '/news/canada/:path*', destination: '/news', permanent: true },
      { source: '/news/doordash-snap-ebt', destination: '/news', permanent: true },
      { source: '/news/iran', destination: '/news', permanent: true },
      { source: '/news/kalshi-:path*', destination: '/news', permanent: true },
      { source: '/news/layoffs/:path*', destination: '/news', permanent: true },
      { source: '/news/newyork/:path*', destination: '/news', permanent: true },
      { source: '/news/samsung-labor-crisis-:path*', destination: '/news', permanent: true },
      { source: '/news/sepp-blatter-:path*', destination: '/news', permanent: true },
      { source: '/news/team-usa-womens-hockey-:path*', destination: '/news', permanent: true },
      { source: '/news/texas/:path*', destination: '/news', permanent: true },
      { source: '/news/ubc-:path*', destination: '/news', permanent: true },
      { source: '/news/ucla-:path*', destination: '/news', permanent: true },
      { source: '/news/vast-freshwater-:path*', destination: '/news', permanent: true },
      { source: '/news/world/:path*', destination: '/news', permanent: true },
      { source: '/news/world-cup-travel-bans-:path*', destination: '/news', permanent: true },
      { source: '/newsarticle/test', destination: '/news', permanent: true },
      { source: '/ngos/:path*', destination: '/news', permanent: true },
      { source: '/nvidia/class-action-:path*', destination: '/nvidia', permanent: true },
      { source: '/nvidia/news/JensenHuang-:path*', destination: '/nvidia', permanent: true },
      { source: '/nvidia/news/indie-devs-:path*', destination: '/nvidia', permanent: true },
      { source: '/nvidia/news/nvidia-4-billion-:path*', destination: '/nvidia', permanent: true },
      { source: '/nvidia/news/nvidia-earth-day-:path*', destination: '/nvidia', permanent: true },
      { source: '/nvidia/news/qualcomm-:path*', destination: '/nvidia', permanent: true },
      { source: '/objectwire', destination: '/news', permanent: true },
      { source: '/open-ai/altman-:path*', destination: '/open-ai', permanent: true },
      { source: '/open-ai/first-ai-:path*', destination: '/open-ai', permanent: true },
      { source: '/open-ai/gpt-5-:path*', destination: '/open-ai', permanent: true },
      { source: '/open-ai/news/:path*', destination: '/open-ai', permanent: true },
      { source: '/open-ai/openai-:path*', destination: '/open-ai', permanent: true },
      { source: '/podcasts/:path*', destination: '/news', permanent: true },
      { source: '/politics/news/:path*', destination: '/news', permanent: true },
      { source: '/profile/[username]', destination: '/profile', permanent: true },
      { source: '/redbull/dance-:path*', destination: '/redbull', permanent: true },
      { source: '/redbull/news/:path*', destination: '/redbull', permanent: true },
      { source: '/research', destination: '/news', permanent: true },
      { source: '/rocket-league', destination: '/news', permanent: true },
      { source: '/saas/apptronik', destination: '/saas', permanent: true },
      { source: '/saas/cognyte', destination: '/saas', permanent: true },
      { source: '/saas/gatik', destination: '/saas', permanent: true },
      { source: '/saas/general-motors', destination: '/saas', permanent: true },
      { source: '/saas/news/ai-:path*', destination: '/saas', permanent: true },
      { source: '/saas/news/chatgpt-:path*', destination: '/saas', permanent: true },
      { source: '/saas/news/introducing-:path*', destination: '/saas', permanent: true },
      { source: '/saas/news/render-:path*', destination: '/saas', permanent: true },
      { source: '/saas/news/sam-altman-:path*', destination: '/saas', permanent: true },
      { source: '/saas/novartis', destination: '/saas', permanent: true },
      { source: '/saas/sailpoint', destination: '/saas', permanent: true },
      { source: '/saas/upside', destination: '/saas', permanent: true },
      { source: '/search/mozilla-firefox', destination: '/search', permanent: true },
      { source: '/service/:path*', destination: '/austin-private-detective-agency', permanent: true },
      { source: '/service', destination: '/austin-private-detective-agency', permanent: true },
      { source: '/social/meta/news/meta-platforms-may-ditch-:path*', destination: '/social', permanent: true },
      { source: '/social/news/:path*', destination: '/social', permanent: true },
      { source: '/social/tiktok/:path*', destination: '/social', permanent: true },
      { source: '/tags/[tag]', destination: '/tags', permanent: true },
      { source: '/team', destination: '/news', permanent: true },
      { source: '/tech/asml-:path*', destination: '/tech', permanent: true },
      { source: '/tech/cloudflare-:path*', destination: '/tech', permanent: true },
      { source: '/tech/deepseek/:path*', destination: '/tech', permanent: true },
      { source: '/tech/digital-realty/:path*', destination: '/tech', permanent: true },
      { source: '/tech/minimax-:path*', destination: '/tech', permanent: true },
      { source: '/tech/newegg/:path*', destination: '/tech', permanent: true },
      { source: '/tech/news/adobe-:path*', destination: '/tech', permanent: true },
      { source: '/tech/news/ai-industry-:path*', destination: '/tech', permanent: true },
      { source: '/tech/news/mozilla-:path*', destination: '/tech', permanent: true },
      { source: '/tech/news/palantir-:path*', destination: '/tech', permanent: true },
      { source: '/tech/news/tenstorrent-:path*', destination: '/tech', permanent: true },
      { source: '/tech/news/tsmc-:path*', destination: '/tech', permanent: true },
      { source: '/tech/news/white-collar-:path*', destination: '/tech', permanent: true },
      { source: '/tech/oracle', destination: '/tech', permanent: true },
      { source: '/tech/palantir-:path*', destination: '/tech', permanent: true },
      { source: '/tech/perplexity/news/crowdstrike-:path*', destination: '/tech', permanent: true },
      { source: '/tech/perplexity/news/perplexity-computer-:path*', destination: '/tech', permanent: true },
      { source: '/tech/real-estate', destination: '/tech', permanent: true },
      { source: '/tech/square/:path*', destination: '/tech', permanent: true },
      { source: '/tech/stripe/:path*', destination: '/tech', permanent: true },
      { source: '/tech/tsmc-:path*', destination: '/tech', permanent: true },
      { source: '/technology/ai-sovereignty-shift', destination: '/technology', permanent: true },
      { source: '/technology/alibaba', destination: '/technology', permanent: true },
      { source: '/technology/articles/:path*', destination: '/technology', permanent: true },
      { source: '/technology/grok-:path*', destination: '/technology', permanent: true },
      { source: '/technology/news/:path*', destination: '/technology', permanent: true },
      { source: '/technology/sanders-:path*', destination: '/technology', permanent: true },
      { source: '/technology/stablecoins/:path*', destination: '/technology', permanent: true },
      { source: '/technology/stablecoins', destination: '/technology', permanent: true },
      { source: '/technology/terrapower/:path*', destination: '/technology', permanent: true },
      { source: '/technology/wordpress-:path*', destination: '/technology', permanent: true },
      { source: '/tiktok', destination: '/news', permanent: true },
      { source: '/tiktok/:path*', destination: '/news', permanent: true },
      { source: '/trump/WLFI-:path*', destination: '/trump', permanent: true },
      { source: '/trump/cbp-:path*', destination: '/trump', permanent: true },
      { source: '/trump/china/:path*', destination: '/trump', permanent: true },
      { source: '/trump/god-:path*', destination: '/trump', permanent: true },
      { source: '/trump/ice-:path*', destination: '/trump', permanent: true },
      { source: '/trump/japan-:path*', destination: '/trump', permanent: true },
      { source: '/trump/kristi-noem/:path*', destination: '/trump', permanent: true },
      { source: '/trump/kristi-noem', destination: '/trump', permanent: true },
      { source: '/trump/musk-:path*', destination: '/trump', permanent: true },
      { source: '/trump/news/:path*', destination: '/trump', permanent: true },
      { source: '/trump/prediction-:path*', destination: '/trump', permanent: true },
      { source: '/trump/shadow-:path*', destination: '/trump', permanent: true },
      { source: '/trump/space-:path*', destination: '/trump', permanent: true },
      { source: '/trump/tax-:path*', destination: '/trump', permanent: true },
      { source: '/trump/trump-ice-:path*', destination: '/trump', permanent: true },
      { source: '/trump/trump-totalenergies-:path*', destination: '/trump', permanent: true },
      { source: '/trump/white-house-app-:path*', destination: '/trump', permanent: true },
      { source: '/video-games/007-first-light/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/007-first-light', destination: '/video-games', permanent: true },
      { source: '/video-games/Digital-Foundry', destination: '/video-games', permanent: true },
      { source: '/video-games/anime/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/ark-raiders/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/ark-raiders', destination: '/video-games', permanent: true },
      { source: '/video-games/battlefield-6/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/bellwright', destination: '/video-games', permanent: true },
      { source: '/video-games/capcom/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/capcom', destination: '/video-games', permanent: true },
      { source: '/video-games/dispatch-:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/dragon-ball/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/epic/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/fortnite/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/fortnite', destination: '/video-games', permanent: true },
      { source: '/video-games/forza-horizon-6/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/forza-horizon-6', destination: '/video-games', permanent: true },
      { source: '/video-games/game-of-the-year-:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/gamestop/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/gta-6/:path*', destination: '/video-games/gta-6', permanent: true },
      { source: '/video-games/mario-kart/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/marvels-wolverine', destination: '/video-games', permanent: true },
      { source: '/video-games/mha/alls-justice', destination: '/video-games', permanent: true },
      { source: '/video-games/mha', destination: '/video-games', permanent: true },
      { source: '/video-games/mha/ultra-rumble', destination: '/video-games', permanent: true },
      { source: '/video-games/mha/ultra-rumble/season-15/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/mha/ultra-rumble/season-15', destination: '/video-games', permanent: true },
      { source: '/video-games/mha/ultra-rumble/season-16/cluster-bakugo', destination: '/video-games/mha/ultra-rumble/season-16', permanent: true },
      { source: '/video-games/mythmatch', destination: '/video-games', permanent: true },
      { source: '/video-games/new/crimson-desert/:path*', destination: '/video-games/new/crimson-desert', permanent: true },
      { source: '/video-games/new/crimson-desert-ai-art-:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/new/slay-the-spire-2', destination: '/video-games', permanent: true },
      { source: '/video-games/new/windrose/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/new/windrose', destination: '/video-games', permanent: true },
      { source: '/video-games/news/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/nintendo/google-:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/nintendo/mar10-:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/nintendo/pokemon-pokopia-:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/pokemon/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/racing/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/rainbow-6-siege', destination: '/video-games', permanent: true },
      { source: '/video-games/resident-evil-requiem/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/resident-evil-requiem', destination: '/video-games', permanent: true },
      { source: '/video-games/star-wars/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/switch2/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/toxic-comando', destination: '/video-games', permanent: true },
      { source: '/video-games/ubisoft', destination: '/video-games', permanent: true },
      { source: '/video-games/unreal-engine/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/valve-corporation/:path*', destination: '/video-games/valve-corporation', permanent: true },
      { source: '/video-games/windrose/:path*', destination: '/video-games', permanent: true },
      { source: '/winter-olympics/:path*', destination: '/news', permanent: true },
      { source: '/winter-olympics', destination: '/news', permanent: true },
      { source: '/world-cup/:path*', destination: '/news', permanent: true },
      { source: '/wwe/:path*', destination: '/news', permanent: true },
      { source: '/wwe', destination: '/news', permanent: true },
      { source: '/youtube/mat-armstrong/:path*', destination: '/youtube', permanent: true },
      { source: '/youtube/mat-armstrong', destination: '/youtube', permanent: true },
      { source: '/youtube/nelk-boys', destination: '/youtube', permanent: true },
      { source: '/youtube/news/:path*', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/arthur-tv', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/behzinga', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/charity-match/england-vs-france-2026', destination: '/youtube/sidemen/charity-match', permanent: true },
      { source: '/youtube/sidemen/george-clark', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/ksi/:path*', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/ksi', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/miniminter', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/news', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/vikkstar', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/w2s', destination: '/youtube', permanent: true },

    ];
  },
  
  // ==========================================================================
  // COMPRESSION & BUILD OPTIMIZATION
  // ==========================================================================
  compress: true,
  productionBrowserSourceMaps: false,
  reactStrictMode: true,
  
  // ==========================================================================
  // EXPERIMENTAL PERFORMANCE FEATURES
  // ==========================================================================
  experimental: {
    // Optimize package imports
    optimizePackageImports: ['lucide-react', '@radix-ui/react-icons'],
  },
};

export default nextConfig;
