import type { Metadata } from 'next';
import Link from 'next/link';
import { SITE_CONFIG } from '@/lib/site-config';

export const metadata: Metadata = {
  title: `Privacy Policy | ${SITE_CONFIG.name}`,
  description: `Privacy Policy for ${SITE_CONFIG.name} — how we collect, use, and protect your information.`,
  alternates: { canonical: `${SITE_CONFIG.url}/privacy-policy` },
};

export default function PrivacyPolicyPage() {
  const year = new Date().getFullYear();

  return (
    <main className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
      <h1 className="font-serif font-bold text-3xl sm:text-4xl text-gray-900 mb-2">
        Privacy Policy
      </h1>
      <p className="text-sm text-gray-500 mb-10">
        Last updated: May 30, 2026 &nbsp;·&nbsp; {SITE_CONFIG.legalName}
      </p>

      <div className="space-y-8 text-gray-700 leading-relaxed">

        <section>
          <h2 className="font-serif font-bold text-xl text-gray-900 mb-3">Who We Are</h2>
          <p>
            {SITE_CONFIG.name} is operated by {SITE_CONFIG.legalName} ("{SITE_CONFIG.publisherName}", "we", "us", or "our").
            We publish news and editorial content at <strong>{SITE_CONFIG.url}</strong>.
            Questions about this policy can be directed to{' '}
            <a href={`mailto:${SITE_CONFIG.email}`} className="text-blue-600 underline hover:text-blue-800">
              {SITE_CONFIG.email}
            </a>.
          </p>
        </section>

        <section>
          <h2 className="font-serif font-bold text-xl text-gray-900 mb-3">Information We Collect</h2>
          <p className="mb-3">We collect information only when you actively provide it or when it is automatically generated by your use of the site.</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>
              <strong>Account information:</strong> If you create an account, we collect your email address and a hashed password. We do not store plaintext passwords.
            </li>
            <li>
              <strong>Newsletter subscriptions:</strong> If you subscribe to our newsletter, your email is processed by Beehiiv, our newsletter provider. See{' '}
              <a href="https://www.beehiiv.com/privacy" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline hover:text-blue-800">Beehiiv's Privacy Policy</a>.
            </li>
            <li>
              <strong>Usage data:</strong> We use Google Analytics (GA4) to collect anonymized analytics including pages visited, session duration, device type, and general geographic region. IP addresses are anonymized by Google before storage.
            </li>
            <li>
              <strong>Cookies:</strong> We use a session cookie for authenticated users. Analytics cookies are set by Google Analytics. We do not use advertising or tracking cookies.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="font-serif font-bold text-xl text-gray-900 mb-3">How We Use Your Information</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>To provide and maintain your account (if you create one)</li>
            <li>To send you newsletters or editorial updates you have subscribed to</li>
            <li>To understand how our content is read and improve editorial coverage</li>
            <li>To detect and prevent abuse or unauthorized access</li>
          </ul>
          <p className="mt-3">
            We do not sell, rent, or share your personal information with third parties for marketing purposes.
          </p>
        </section>

        <section>
          <h2 className="font-serif font-bold text-xl text-gray-900 mb-3">Data Retention</h2>
          <p>
            Account data is retained as long as your account is active. You may delete your account at any time by contacting us at{' '}
            <a href={`mailto:${SITE_CONFIG.email}`} className="text-blue-600 underline hover:text-blue-800">
              {SITE_CONFIG.email}
            </a>.
            Analytics data is retained for 14 months by Google Analytics per their default policy.
          </p>
        </section>

        <section>
          <h2 className="font-serif font-bold text-xl text-gray-900 mb-3">Third-Party Services</h2>
          <p className="mb-2">This site uses the following third-party services that may process data:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Supabase</strong> — authentication and database hosting. Data is stored in US-East data centers. <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline hover:text-blue-800">Privacy Policy</a></li>
            <li><strong>Google Analytics (GA4)</strong> — anonymized usage analytics. <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline hover:text-blue-800">Privacy Policy</a></li>
            <li><strong>Beehiiv</strong> — newsletter delivery. <a href="https://www.beehiiv.com/privacy" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline hover:text-blue-800">Privacy Policy</a></li>
          </ul>
        </section>

        <section>
          <h2 className="font-serif font-bold text-xl text-gray-900 mb-3">Your Rights</h2>
          <p>
            Depending on your jurisdiction, you may have rights to access, correct, or delete your personal data. To exercise these rights, contact us at{' '}
            <a href={`mailto:${SITE_CONFIG.email}`} className="text-blue-600 underline hover:text-blue-800">
              {SITE_CONFIG.email}
            </a>.
            Residents of the European Economic Area (EEA) and California have additional rights under GDPR and CCPA respectively.
          </p>
        </section>

        <section>
          <h2 className="font-serif font-bold text-xl text-gray-900 mb-3">Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy to reflect changes in our practices or applicable law. Material changes will be noted with an updated "Last updated" date at the top of this page.
          </p>
        </section>

        <section>
          <h2 className="font-serif font-bold text-xl text-gray-900 mb-3">Contact</h2>
          <p>
            For privacy-related questions, contact:{' '}
            <a href={`mailto:${SITE_CONFIG.email}`} className="text-blue-600 underline hover:text-blue-800">
              {SITE_CONFIG.email}
            </a>
          </p>
        </section>

        <p className="text-xs text-gray-400 border-t pt-6">
          &copy; {year} {SITE_CONFIG.legalName}. See also:{' '}
          <Link href="/terms-of-service" className="underline hover:text-gray-600">Terms of Service</Link>
          {' '}·{' '}
          <Link href="/editorial-standards" className="underline hover:text-gray-600">Editorial Standards</Link>
        </p>
      </div>
    </main>
  );
}
