export const SITE_CONFIG = {
  name: "OzoneNews",
  legalName: "Ozone Network News LLC",
  publisherName: "Ozone Network News",
  url: "https://www.ozonenetwork.news",
  description: "Verified reporting on video games, startup companies, and finance. The intel desk for builders, investors, and players.",
  tagline: "Gaming · Finance · Startups",
  locale: "en_US",
  author: "OzoneNews Editorial Team",
  email: "editorial@ozonenetwork.news",
  twitter: "@ozonenetwork",
  // /opengraph-image is auto-generated by app/opengraph-image.tsx (1200x630 brand card).
  // Falls back to the static logo for contexts that don't support dynamic OG images.
  socialImage: "https://www.ozonenetwork.news/opengraph-image",
  defaultOgImage: "https://www.ozonenetwork.news/opengraph-image",
  logo: "https://www.ozonenetwork.news/ozonenews-logo.png",
  // Off-domain entity verification — populated as accounts go live.
  sameAs: [
    "https://twitter.com/ozonenetwork",
    "https://www.linkedin.com/company/ozonenetwork",
  ],
};

export const BLOCKED_USER_AGENTS = [
  'CCBot',
];

export const TRACKING_PARAMS = [
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'fbclid',
  'gclid',
];

export const DUPLICATE_PARAMS = [
  'ref',
  'source',
  'campaign',
];
