export const SITE_CONFIG = {
  name: "OzoneNews",
  url: "https://www.ozonenetwork.news",
  description: "Breaking news, technology, and digital culture",
  tagline: "Tech, Gaming, Crypto & Culture News 2026",
  locale: "en_US",
  author: "OzoneNews Editorial Team",
  email: "contact@ozonenetwork.news",
  twitter: "@ozonedailynews",
  // /opengraph-image is auto-generated by app/opengraph-image.tsx (1200x630 brand card).
  // Falls back to the static logo for contexts that don't support dynamic OG images.
  socialImage: "https://www.ozonenetwork.news/opengraph-image",
  defaultOgImage: "https://www.ozonenetwork.news/opengraph-image",
};

export const BLOCKED_USER_AGENTS = [
  'CCBot',
];

export const TRACKING_PARAMS = [
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'fbclid',
  'gclid',
];

export const DUPLICATE_PARAMS = [
  'ref',
  'source',
  'campaign',
];
