// =============================================================================
// SITE-WIDE SEO CONFIG - Single Source of Truth
// All SEO settings, routes, and governance rules in one place
// =============================================================================

export const SITE_CONFIG = {
  // Base configuration
  name: 'ObjectWire',
  tagline: 'Precision Intelligence News Network',
  description: 'ObjectWire delivers verified, source-cited intelligence on business, technology, and policy.',
  url: 'https://www.objectwire.org', // WWW is canonical (Squarespace requirement)
  locale: 'en_US',
  
  // Contact
  email: 'contact@objectwire.org',
  correctionsEmail: 'corrections@objectwire.org',
  aiPartnershipsEmail: 'ai@objectwire.org',
  
  // Social
  social: {
    twitter: 'https://twitter.com/objectwire',
    linkedin: 'https://www.linkedin.com/company/objectwire',
    facebook: 'https://www.facebook.com/objectwire',
  },
  
  // Images
  defaultOgImage: '/og-image.png',
  logo: '/logo.png',
  logoWidth: 600,
  logoHeight: 60,
  
  // Founding
  foundingDate: '2024',
} as const;

// =============================================================================
// ROUTE REGISTRY - All valid routes with SEO metadata
// =============================================================================

export interface RouteConfig {
  path: string;
  title: string;
  description: string;
  priority: number;
  changeFrequency: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  indexable: boolean;
  includeInNewsSitemap: boolean;
  type: 'static' | 'wiki' | 'news' | 'category' | 'utility' | 'article' | 'unknown';
}

export const ROUTE_REGISTRY: RouteConfig[] = [
  {
    path: '/2025-nissan-z-vs-toyota-gr-supra-comparison',
    title: '2025 Nissan Z Vs Toyota Gr Supra Comparison',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/alphabet-inc-the-history-of-google',
    title: 'Alphabet Inc The History Of Google',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/alphabet-or-nvidia-here-s-who-i-think-will-win-the-ai-chip-war',
    title: 'Alphabet Or Nvidia Here S Who I Think Will Win The Ai Chip War',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/analyst',
    title: 'Analyst',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/asset-collection',
    title: 'Asset Collection',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/austin-private-detective-agency',
    title: 'Austin Private Detective Agency',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/black-lady-blacklives-matter',
    title: 'Black Lady Blacklives Matter',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/blitzy-ai-powered-autonomous-software-development',
    title: 'Blitzy Ai Powered Autonomous Software Development',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/case',
    title: 'Case',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/chatgpt-staffers-to-offer-secondary-sale-at-500b-valuation',
    title: 'Chatgpt Staffers To Offer Secondary Sale At 500b Valuation',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/clear-cache',
    title: 'Clear Cache',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/coding/nestjs-vs-nextjs-express',
    title: 'Nestjs Vs Nextjs Express',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/cognyte-software-ltd-cgnt',
    title: 'Cognyte Software Ltd Cgnt',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/comet-ai-web-browser-vs-atlas-by-chatgpt',
    title: 'Comet Ai Web Browser Vs Atlas By Chatgpt',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/does-doordash-take-snap',
    title: 'Does Doordash Take Snap',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/fact-finding-and-evidence-collection',
    title: 'Fact Finding And Evidence Collection',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/finance',
    title: 'Finance',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/finance/articles/16-trillion-on-chain-tokenization-revolution-2026',
    title: '16 Trillion On Chain Tokenization Revolution 2026',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/finance/articles/nasdaq-proposed-24-7-trading',
    title: 'Nasdaq Proposed 24 7 Trading',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/finance/articles/oanda-or-interactive-brokers-forex-trading-usa',
    title: 'Oanda Or Interactive Brokers Forex Trading Usa',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/finance/articles/starlink-economic-analysis',
    title: 'Starlink Economic Analysis',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/finance/articles/statistical-edge-permutation-testing-trading',
    title: 'Statistical Edge Permutation Testing Trading',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/finance/articles/the-2026-sovereign-squeeze-ai-nuclear-age',
    title: 'The 2026 Sovereign Squeeze Ai Nuclear Age',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/finance/articles/the-greenland-fulcrum-and-the-golden-dome-architecture',
    title: 'The Greenland Fulcrum And The Golden Dome Architecture',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/finance/articles/the-trillion-dollar-treasure-trove-in-the-deep-sea',
    title: 'The Trillion Dollar Treasure Trove In The Deep Sea',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/get-help',
    title: 'Get Help',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/github-universe-october-28th-and-29th-san-francisco',
    title: 'Github Universe October 28th And 29th San Francisco',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/hedera-vs-solana-for-dapps',
    title: 'Hedera Vs Solana For Dapps',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/infidelity',
    title: 'Infidelity',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/introducing-bitchat-jack-dorsey',
    title: 'Introducing Bitchat Jack Dorsey',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/jerome-powell-federal-reserve-headquarters-renovation',
    title: 'Jerome Powell Federal Reserve Headquarters Renovation',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/luxury-watch-heists-at-the-us-grand-prix',
    title: 'Luxury Watch Heists At The Us Grand Prix',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/missing-persons',
    title: 'Missing Persons',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/nasdaq-proposed-24-7-trading',
    title: 'Nasdaq Proposed 24 7 Trading',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/neurophos-ai-hardware-startup',
    title: 'Neurophos Ai Hardware Startup',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/non-degree-studies-at-university-of-texas-austin',
    title: 'Non Degree Studies At University Of Texas Austin',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/nycs-ranked-choice-voting-system-faces-scrutiny',
    title: 'Nycs Ranked Choice Voting System Faces Scrutiny',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/oh-canada-what-has-happened',
    title: 'Oh Canada What Has Happened',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/pegatron-opens-us-factory-tx',
    title: 'Pegatron Opens Us Factory Tx',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/prophet-ebo-noah-s-flood-prophecy',
    title: 'Prophet Ebo Noah S Flood Prophecy',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/render-vs-vercel-for-free-start-up-app-deployment',
    title: 'Render Vs Vercel For Free Start Up App Deployment',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/sam-altman-visits-hedera-team',
    title: 'Sam Altman Visits Hedera Team',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/start-up-news',
    title: 'Start Up News',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/surveillance',
    title: 'Surveillance',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/technology',
    title: 'Technology',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/terms-of-service',
    title: 'Terms Of Service',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/the-intercept-sues-doge',
    title: 'The Intercept Sues Doge',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/txc-stable-coin',
    title: 'Txc Stable Coin',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/who-is-serge-gatari-ai-course-review',
    title: 'Who Is Serge Gatari Ai Course Review',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/007-first-light',
    title: '007 First Light',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/apple',
    title: 'Apple',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/apple/apple-iphone-18-delay-2027-foldable',
    title: 'Apple Iphone 18 Delay 2027 Foldable',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/apple-google-gemini-partnership',
    title: 'Apple Google Gemini Partnership',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/artists',
    title: 'Artists',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/artists/don-toliver',
    title: 'Don Toliver',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/artists/don-toliver/octane-review-features',
    title: 'Octane Review Features',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/artists/drake',
    title: 'Drake',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/artists/yeat',
    title: 'Yeat',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/austin/19th-century-Austin-home-once-owned-Elijah-Wood-listed-at-3.2M',
    title: '19th Century Austin Home Once Owned Elijah Wood Listed At 3.2M',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/austin-private-detective-agency/infidelity',
    title: 'Infidelity',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/austin-private-detective-agency/missing-persons',
    title: 'Missing Persons',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/austin-private-detective-agency/surveillance',
    title: 'Surveillance',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/austins-reign-as-a-tech-hub-might-be-coming-to-an-end',
    title: 'Austins Reign As A Tech Hub Might Be Coming To An End',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/bank-of-america',
    title: 'Bank Of America',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/beastgames',
    title: 'Beastgames',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/beastgames/season-2',
    title: 'Season 2',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/blitzy-ai-powered-autonomous-software-development-platform-developer-review-for-2025',
    title: 'Blitzy Ai Powered Autonomous Software Development Platform Developer Review For 2025',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/chicos-toxicos',
    title: 'Chicos Toxicos',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/coding/nestjs-vs-nextjs-vs-express',
    title: 'Nestjs Vs Nextjs Vs Express',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/contributors/conan-boyle',
    title: 'Conan Boyle',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/contributors/jack-wang',
    title: 'Jack Wang',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/davos',
    title: 'Davos',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/davos/all-in-podcast',
    title: 'All In Podcast',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/davos/all-in-podcast/david-sacks',
    title: 'David Sacks',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/davos/all-in-podcast/jason',
    title: 'Jason',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/elon-musk/spacex',
    title: 'Spacex',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/elon-musk/sun-shading-the-billionaire-wants-ai-satellites-to-block-the-sun',
    title: 'Sun Shading The Billionaire Wants Ai Satellites To Block The Sun',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/example-investigation',
    title: 'Example Investigation',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/gatik',
    title: 'Gatik',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/github',
    title: 'Github',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/google',
    title: 'Google',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/google/agentic-vision',
    title: 'Agentic Vision',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/google/agentic-vision/gemini-3-flash',
    title: 'Gemini 3 Flash',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/google/waymo',
    title: 'Waymo',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/google/waymo/ntsb-investigation-school-bus-violations',
    title: 'Ntsb Investigation School Bus Violations',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/hashicorp',
    title: 'Hashicorp',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/https-www-eatcookjoy-com',
    title: 'Https Www Eatcookjoy Com',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/index',
    title: 'Index',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/influencer/mrbeast-launches-beast-games-season-2-casting',
    title: 'Mrbeast Launches Beast Games Season 2 Casting',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/influencer/steve-will-do-it-kicked-of-logan-paul-s-podcast-making-an-official-return-to-youtube',
    title: 'Steve Will Do It Kicked Of Logan Paul S Podcast Making An Official Return To Youtube',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/intel',
    title: 'Intel',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/intel/18a-high-volume-manufacturing',
    title: '18a High Volume Manufacturing',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/introducing-bitchat-jack-dorseys-game-changing-bluetooth-mesh-messaging-app',
    title: 'Introducing Bitchat Jack Dorseys Game Changing Bluetooth Mesh Messaging App',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/iran',
    title: 'Iran',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/ironspring-ventures-startups-are-changing-construction-goodship-track3d-fleetpulse',
    title: 'Ironspring Ventures Startups Are Changing Construction Goodship Track3d Fleetpulse',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/james-cameron-wiki',
    title: 'James Cameron Wiki',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/lifetime-fitness-austin-new-location-opening-in-2025-november-1301-south-lamar',
    title: 'Lifetime Fitness Austin New Location Opening In 2025 November 1301 South Lamar',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/marvels-wolverine',
    title: 'Marvels Wolverine',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/meta-platforms-may-ditch-nvidia-for-googles-parent-company-tpus-custom-compute-chips-for-ai',
    title: 'Meta Platforms May Ditch Nvidia For Googles Parent Company Tpus Custom Compute Chips For Ai',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/mha',
    title: 'Mha',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/mha/ultra-rumble',
    title: 'Ultra Rumble',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/mha/ultra-rumble/season-15',
    title: 'Season 15',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/microsoft',
    title: 'Microsoft',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/minesoda',
    title: 'Minesoda',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/minesoda/Ilhan-Omar',
    title: 'Ilhan Omar',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/minesoda/nick-shirley-drops-second-part-of-fraud-investigation',
    title: 'Nick Shirley Drops Second Part Of Fraud Investigation',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/mozilla-firefox',
    title: 'Mozilla Firefox',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/nasa',
    title: 'Nasa',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/nasa/europa',
    title: 'Europa',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/nasa/europa/juno-ice-shell-18-miles-thick',
    title: 'Juno Ice Shell 18 Miles Thick',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/nelk-boys',
    title: 'Nelk Boys',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/altman-amodei-condemn-ice-shooting-praise-trump',
    title: 'Altman Amodei Condemn Ice Shooting Praise Trump',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/bank-of-america-nvidia-ai-software-too-hard',
    title: 'Bank Of America Nvidia Ai Software Too Hard',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/california-joins-who-disease-network-after-us-withdrawal',
    title: 'California Joins Who Disease Network After Us Withdrawal',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/gatik-first-us-driverless-trucks-commercially',
    title: 'Gatik First Us Driverless Trucks Commercially',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/google-launches-ai-plus-in-us',
    title: 'Google Launches Ai Plus In Us',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/hashicorp-vault-identity-based-secrets-management-blockchain-security',
    title: 'Hashicorp Vault Identity Based Secrets Management Blockchain Security',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/johns-hopkins-psychedelic-psychiatry-clinical-guidance',
    title: 'Johns Hopkins Psychedelic Psychiatry Clinical Guidance',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/microsoft-gave-fbi-bitlocker-keys',
    title: 'Microsoft Gave Fbi Bitlocker Keys',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/minneapolis-clergy-arrested-ice-protest-pam-bondi-don-lemon',
    title: 'Minneapolis Clergy Arrested Ice Protest Pam Bondi Don Lemon',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/minnesota-feeding-our-future-fraud',
    title: 'Minnesota Feeding Our Future Fraud',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/mozilla-deploys-1-4b-to-challenge-openai-anthropic',
    title: 'Mozilla Deploys 1 4b To Challenge Openai Anthropic',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/novartis-sixth-drugmaker-supreme-court-medicare-negotiations',
    title: 'Novartis Sixth Drugmaker Supreme Court Medicare Negotiations',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/openai-vs-elon-musk-lawsuit-financial-burn-2026',
    title: 'Openai Vs Elon Musk Lawsuit Financial Burn 2026',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/quantum-computing',
    title: 'Quantum Computing',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/quantum-computing/d-wave-quantum-optimization-breakthrough',
    title: 'D Wave Quantum Optimization Breakthrough',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/spacex-fcc-ai-data-center-satellites',
    title: 'Spacex Fcc Ai Data Center Satellites',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/trump-credit-card-rate-cap-deadline-banks-have-questions',
    title: 'Trump Credit Card Rate Cap Deadline Banks Have Questions',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/trump-microsoft-data-centers-electricity-prices',
    title: 'Trump Microsoft Data Centers Electricity Prices',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/trump-tech-force-white-house-ai-recruitment-drive',
    title: 'Trump Tech Force White House Ai Recruitment Drive',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/ubc-crispr-topical-gene-therapy-skin',
    title: 'Ubc Crispr Topical Gene Therapy Skin',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/news/winter-storm-senate-vote-shutdown-deadline',
    title: 'Winter Storm Senate Vote Shutdown Deadline',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/nintendo',
    title: 'Nintendo',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/nintendo/google-project-genie-ai-knockoffs',
    title: 'Google Project Genie Ai Knockoffs',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/novartis',
    title: 'Novartis',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/nvidia',
    title: 'Nvidia',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/podcasts/all-in-podcast',
    title: 'All In Podcast',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/podcasts/joe-rogan',
    title: 'Joe Rogan',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/resident-evil-requiem',
    title: 'Resident Evil Requiem',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/search',
    title: 'Search',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/semiconductor-supplier-asml-to-open-in-hutto-co-op-district',
    title: 'Semiconductor Supplier Asml To Open In Hutto Co Op District',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/sidemen',
    title: 'Sidemen',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/sidemen/behzinga',
    title: 'Behzinga',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/sidemen/ksi',
    title: 'Ksi',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/sidemen/miniminter',
    title: 'Miniminter',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/sidemen/tbjzl',
    title: 'Tbjzl',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/sidemen/vikkstar',
    title: 'Vikkstar',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/sidemen/w2s',
    title: 'W2s',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/sidemen/zerkaa',
    title: 'Zerkaa',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/silicon-labs-silacon-what-robotos-do-they-work-on',
    title: 'Silicon Labs Silacon What Robotos Do They Work On',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/superintelligence-force-meta-into-their-4th-restructuring-this-year',
    title: 'Superintelligence Force Meta Into Their 4th Restructuring This Year',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/survivor',
    title: 'Survivor',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/sxsw',
    title: 'Sxsw',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/team',
    title: 'Team',
    description: 'TODO: Add description',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'unknown',
  },
  {
    path: '/texas-instruments-ti-cc23xx-and-cc26xx-long-range-low-energy-mesh-for-edge-computing',
    title: 'Texas Instruments Ti Cc23xx And Cc26xx Long Range Low Energy Mesh For Edge Computing',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/tiktok/Announcement-from-the-new-TikTok-USDS-Joint-Venture-LLC',
    title: 'Announcement From The New TikTok USDS Joint Venture LLC',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/trump/donald-trump-sues-jpmorgan-chase-5-billion-lawsuit',
    title: 'Donald Trump Sues Jpmorgan Chase 5 Billion Lawsuit',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/trump/newborn-investment-accounts-wealth-building',
    title: 'Newborn Investment Accounts Wealth Building',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/video-games/top-10-anime-games-2026',
    title: 'Top 10 Anime Games 2026',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/world-cup',
    title: 'World Cup',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/world-cup/boycott-calls-ice-immigration',
    title: 'Boycott Calls Ice Immigration',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  {
    path: '/world-cup/boycott-controversy',
    title: 'Boycott Controversy',
    description: 'TODO: Add description',
    priority: 0.7,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: true,
    type: 'article',
  },
  // ==========================================================================
  // CORE PAGES (Always index)
  // ==========================================================================
  {
    path: '/',
    title: 'ObjectWire | Precision Intelligence News Network',
    description: 'ObjectWire delivers verified, source-cited intelligence on business, technology, and policy.',
    priority: 1.0,
    changeFrequency: 'daily',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'static',
  },
  {
    path: '/about',
    title: 'About ObjectWire',
    description: 'Learn about ObjectWire, our mission, editorial team, and commitment to verified journalism.',
    priority: 0.5,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'static',
  },
  {
    path: '/contact',
    title: 'Contact Us',
    description: 'Get in touch with ObjectWire for tips, corrections, partnerships, or general inquiries.',
    priority: 0.4,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'static',
  },
  {
    path: '/editorial-standards',
    title: 'Editorial Standards',
    description: 'Our commitment to accuracy, fairness, and transparency in journalism.',
    priority: 0.6,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'static',
  },
  {
    path: '/corrections',
    title: 'Corrections Policy',
    description: 'How we handle corrections and updates to our published content.',
    priority: 0.4,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'static',
  },
  {
    path: '/privacy-policy',
    title: 'Privacy Policy',
    description: 'How ObjectWire collects, uses, and protects your personal information.',
    priority: 0.3,
    changeFrequency: 'yearly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'utility',
  },
  
  // ==========================================================================
  // CATEGORY HUBS (High priority for SEO)
  // ==========================================================================
  {
    path: '/news',
    title: 'News',
    description: 'Latest verified news coverage from ObjectWire on business, technology, and policy.',
    priority: 0.9,
    changeFrequency: 'hourly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'category',
  },
  {
    path: '/blog',
    title: 'Blog',
    description: 'In-depth articles, analysis, and commentary from ObjectWire.',
    priority: 0.8,
    changeFrequency: 'daily',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'category',
  },
  {
    path: '/opinion',
    title: 'Opinion',
    description: 'Expert opinion and commentary on current events and industry trends.',
    priority: 0.7,
    changeFrequency: 'daily',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'category',
  },
  {
    path: '/health',
    title: 'Health News',
    description: 'Health and medical news coverage from ObjectWire.',
    priority: 0.7,
    changeFrequency: 'daily',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'category',
  },
  {
    path: '/coding',
    title: 'Coding & Development',
    description: 'Programming, software development, and tech tutorials.',
    priority: 0.7,
    changeFrequency: 'daily',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'category',
  },
  
  // ==========================================================================
  // WIKI/ENCYCLOPEDIA PAGES (High priority, high value)
  // ==========================================================================
  {
    path: '/trump',
    title: 'Donald Trump - Complete Biography and Presidency',
    description: 'Comprehensive information about Donald J. Trump, 45th and 47th President of the United States.',
    priority: 0.9,
    changeFrequency: 'daily',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'wiki',
  },
  {
    path: '/tiktok',
    title: 'TikTok - Complete Guide',
    description: 'Comprehensive guide to TikTok, the social media platform.',
    priority: 0.9,
    changeFrequency: 'daily',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'wiki',
  },
  {
    path: '/james-cameron',
    title: 'James Cameron - Filmmaker & Explorer',
    description: 'James Cameron is a Canadian filmmaker and deep-sea explorer. Director of Avatar, Titanic, and The Terminator franchise.',
    priority: 0.8,
    changeFrequency: 'weekly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'wiki',
  },
  
  // ==========================================================================
  // AUTHOR PAGES
  // ==========================================================================
  {
    path: '/author/conan-d',
    title: 'Conan D | Author & Journalist',
    description: 'Conan D is a journalist and podcaster at ObjectWire specializing in narrative journalism and long-form interviews.',
    priority: 0.6,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'static',
  },
  {
    path: '/author/jack-s',
    title: 'Jack S | Author & Journalist',
    description: 'Jack S is a journalist at ObjectWire committed to ethical journalism and fact-based reporting.',
    priority: 0.6,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'static',
  },
  
  // ==========================================================================
  // SERVICE PAGES
  // ==========================================================================
  {
    path: '/service/photography-videography-austin-tx',
    title: 'Photography & Videography Services | Austin, TX',
    description: 'Professional photography and videography services for investigative, legal, and private documentation purposes.',
    priority: 0.6,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'static',
  },
  {
    path: '/service/press-release',
    title: 'PR, Branding & Press Release Services',
    description: 'Professional PR, branding, and press release writing services for Austin-based businesses, startups, and nonprofits.',
    priority: 0.6,
    changeFrequency: 'monthly',
    indexable: true,
    includeInNewsSitemap: false,
    type: 'static',
  },
  
  // ==========================================================================
  // NO-INDEX PAGES (Never crawl/index)
  // ==========================================================================
  {
    path: '/admin',
    title: 'Admin',
    description: '',
    priority: 0,
    changeFrequency: 'never',
    indexable: false,
    includeInNewsSitemap: false,
    type: 'utility',
  },
  {
    path: '/api',
    title: 'API',
    description: '',
    priority: 0,
    changeFrequency: 'never',
    indexable: false,
    includeInNewsSitemap: false,
    type: 'utility',
  },
  {
    path: '/preview',
    title: 'Preview',
    description: '',
    priority: 0,
    changeFrequency: 'never',
    indexable: false,
    includeInNewsSitemap: false,
    type: 'utility',
  },
];

// =============================================================================
// URL NORMALIZATION RULES
// =============================================================================

/**
 * Normalize a URL slug
 */
export function normalizeSlug(slug: string): string {
  return slug
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/_+/g, '-')
    .replace(/[^a-z0-9-/]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

/**
 * Normalize a full URL path
 */
export function normalizePath(path: string): string {
  return path
    .toLowerCase()
    .replace(/\/+/g, '/')
    .replace(/\/$/, '')
    .replace(/^(?!\/)/, '/');
}

/**
 * Get canonical URL for a path
 */
export function getCanonicalUrl(path: string): string {
  return `${SITE_CONFIG.url}${normalizePath(path)}`;
}

// =============================================================================
// REDIRECT RULES
// =============================================================================

export interface RedirectRule {
  source: string;
  destination: string;
  permanent: boolean;
}

export const REDIRECT_RULES: RedirectRule[] = [
  // Trump variations
  { source: '/donaldtrump', destination: '/trump', permanent: true },
  { source: '/donald-trump', destination: '/trump', permanent: true },
  { source: '/president-trump', destination: '/trump', permanent: true },
  { source: '/trump-wiki', destination: '/trump', permanent: true },
  
  // TikTok variations
  { source: '/tik-tok', destination: '/tiktok', permanent: true },
  { source: '/tik_tok', destination: '/tiktok', permanent: true },
  
  // James Cameron variations
  { source: '/cameron', destination: '/james-cameron', permanent: true },
  { source: '/jamescameron', destination: '/james-cameron', permanent: true },
  
  // Old URL patterns
  { source: '/articles', destination: '/blog', permanent: true },
  { source: '/posts', destination: '/blog', permanent: true },
];

// =============================================================================
// BLOCKED PARAMETERS (Strip from URLs)
// =============================================================================

export const TRACKING_PARAMS = [
  // UTM parameters
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'utm_term',
  'utm_content',
  'utm_id',
  
  // Referral tracking
  'ref',
  'referrer',
  'source',
  
  // Ad platform tracking
  'fbclid',
  'gclid',
  'gclsrc',
  'msclkid',
  'dclid',
  'zanpid',
  
  // Analytics
  '_ga',
  '_gl',
  'mc_cid',
  'mc_eid',
  
  // Social
  'igshid',
  'twclid',
  
  // Other
  'oly_enc_id',
  'oly_anon_id',
  'vero_id',
  '__s',
  '_hsenc',
  '_hsmi',
  'mkt_tok',
] as const;

export const DUPLICATE_PARAMS = [
  'sort',
  'filter',
  'view',
  'order',
  'page', // For non-paginated content
] as const;

// =============================================================================
// BLOCKED CRAWLERS
// =============================================================================

export const BLOCKED_USER_AGENTS = [
  'AhrefsBot',
  'SemrushBot',
  'MJ12bot',
  'DotBot',
  'BLEXBot',
  'DataForSeoBot',
  'serpstatbot',
  'Bytespider',
] as const;

// =============================================================================
// ROUTE HELPERS
// =============================================================================

/**
 * Get route config by path
 */
export function getRouteConfig(path: string): RouteConfig | undefined {
  const normalized = normalizePath(path);
  return ROUTE_REGISTRY.find(r => r.path === normalized);
}

/**
 * Check if a path should be indexed
 */
export function shouldIndex(path: string): boolean {
  const config = getRouteConfig(path);
  if (config) return config.indexable;
  
  // Default checks for unknown paths
  const normalized = normalizePath(path);
  if (normalized.startsWith('/api')) return false;
  if (normalized.startsWith('/admin')) return false;
  if (normalized.startsWith('/preview')) return false;
  if (normalized.includes('draft')) return false;
  
  return true;
}

/**
 * Check if a path should be in news sitemap
 */
export function shouldIncludeInNewsSitemap(path: string): boolean {
  const config = getRouteConfig(path);
  return config?.includeInNewsSitemap ?? false;
}

/**
 * Get all indexable routes
 */
export function getIndexableRoutes(): RouteConfig[] {
  return ROUTE_REGISTRY.filter(r => r.indexable);
}

/**
 * Get redirect for a path
 */
export function getRedirect(path: string): RedirectRule | undefined {
  const normalized = normalizePath(path);
  return REDIRECT_RULES.find(r => normalizePath(r.source) === normalized);
}

// =============================================================================
// EXPORTS
// =============================================================================

export default {
  SITE_CONFIG,
  ROUTE_REGISTRY,
  REDIRECT_RULES,
  TRACKING_PARAMS,
  DUPLICATE_PARAMS,
  BLOCKED_USER_AGENTS,
  normalizeSlug,
  normalizePath,
  getCanonicalUrl,
  getRouteConfig,
  shouldIndex,
  shouldIncludeInNewsSitemap,
  getIndexableRoutes,
  getRedirect,
};
