/**
 * Permanent 301 redirects for ObjectWire.
 *
 * HOW TO ADD:    Push an entry to the correct section array below.
 * HOW TO REMOVE: Delete or comment out the entry.
 * HOW TO TEST:   npm run dev, then curl -I https://localhost:3000/old-path
 *
 * Sections:
 *   BLOG_MIGRATIONS   - old /blog/* paths
 *   TAGS              - /tags/* → /news
 *   HUBS              - hub pages that moved or merged
 *   ARTICLES          - individual article redirects
 *   WILDCARDS         - catch-all :path* patterns (cheapest, load first)
 *   NON_RANKING       - GSC cleanup sweeps
 */

type R = { source: string; destination: string; permanent: boolean };

export const redirects: R[] = [
      // Blog URL migration - old /blog/ paths to root
      {
        source: '/blog/sam-altman-visits-hedera-team',
        destination: '/sam-altman-visits-hedera-team',
        permanent: true, // 301 redirect
      },
      
      // Blitzy review URL consolidation
      {
        source: '/blitzy-ai-powered-autonomous-software-development-platform-developer-review-for-2025',
        destination: '/blitzy-ai-powered-autonomous-software-development',
        permanent: true, // 301 redirect
      },
      
      // ==========================================================================
      // SIDEMEN CONTENT MIGRATION - Moved from /sidemen to /youtube/sidemen
      // Date: February 7, 2026
      // ==========================================================================
      
      // Main Sidemen hub page
      {
        source: '/sidemen',
        destination: '/youtube/sidemen',
        permanent: true,
      },
      
      // Individual Sidemen member pages
      {
        source: '/sidemen/ksi',
        destination: '/youtube/sidemen/ksi',
        permanent: true,
      },
      {
        source: '/sidemen/miniminter',
        destination: '/youtube/sidemen/miniminter',
        permanent: true,
      },
      {
        source: '/sidemen/zerkaa',
        destination: '/youtube/sidemen/zerkaa',
        permanent: true,
      },
      {
        source: '/sidemen/tbjzl',
        destination: '/youtube/sidemen/tbjzl',
        permanent: true,
      },
      {
        source: '/sidemen/behzinga',
        destination: '/youtube/sidemen/behzinga',
        permanent: true,
      },
      {
        source: '/sidemen/vikkstar',
        destination: '/youtube/sidemen/vikkstar',
        permanent: true,
      },
      {
        source: '/sidemen/w2s',
        destination: '/youtube/sidemen/w2s',
        permanent: true,
      },
      
      // Wildcard catch-all for any other /sidemen/* paths
      {
        source: '/sidemen/:path*',
        destination: '/youtube/sidemen/:path*',
        permanent: true,
      },

      // ==========================================================================
      // CRYPTO CONTENT MIGRATION - /crypto hub restored, only wiki-style
      // definitions still redirect to /define/crypto/*
      // Date: April 2, 2026
      // ==========================================================================

      {
        source: '/crypto/tether',
        destination: '/define/crypto/tether',
        permanent: true,
      },
      {
        source: '/crypto/txc-stablecoin',
        destination: '/define/crypto/txc-stablecoin',
        permanent: true,
      },

      // ==========================================================================
      // CONTENT CONSOLIDATION — May 2026
      // 584 non-top-100 pages redirected to their nearest hub or /news
      // ==========================================================================
      { source: '/airlines/jetblue/jetblue-surveillance-pricing-lawsuit-personal-data-2026', destination: '/news', permanent: true },
      { source: '/amazon/news/amazon-1-hour-3-hour-delivery-us-launch-march-2026', destination: '/amazon', permanent: true },
      { source: '/amazon/news/amazon-acquires-fauna-robotics-sprout-humanoid', destination: '/amazon', permanent: true },
      { source: '/amazon/news/amazon-one-medical-glp1-hims-hers-price-war-2026', destination: '/amazon', permanent: true },
      { source: '/amazon/news/andy-jassy-2025-pay-2-1-million-30-percent-raise', destination: '/amazon', permanent: true },
      { source: '/amazon/news/andy-jassy-ai-will-reduce-headcount-many-roles-cnbc-february-2026', destination: '/amazon', permanent: true },
      { source: '/amazon/news/aws-uae-data-center-fire-iran-strikes-march-2026', destination: '/amazon', permanent: true },
      { source: '/apple/apple-iphone-18-delay-2027-foldable', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-50th-anniversary-apple-park-grand-finale-2026', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-ceo-transition-tim-cook-steps-down-john-ternus-2026', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-google-gemini-partnership', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-march-2026-products-macbook-iphone-17e-ipad-air-m5', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-post-iphone-gurman-6-secret-products-ambient-ai-2026', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-removes-anything-vibe-coding-app-store-2026', destination: '/apple', permanent: true },
      { source: '/apple/news/apple-video-podcasts-youtube', destination: '/apple', permanent: true },
      { source: '/apple/news/california-based-act-antitrust-sb1074-2026', destination: '/apple', permanent: true },
      { source: '/apple/news/f1-apple-tv-espn-domenicali', destination: '/apple', permanent: true },
      { source: '/apple/news/mac-mini-houston-tx', destination: '/apple', permanent: true },
      { source: '/articlepage/test', destination: '/news', permanent: true },
      { source: '/artists/don-toliver/octane-review-features', destination: '/news', permanent: true },
      { source: '/artists', destination: '/news', permanent: true },
      { source: '/austin/michael-dell-750-million-ut-austin-ai-hospital-2026', destination: '/tech', permanent: true },
      { source: '/austin/waymo-city-council-bufords-ambulance-obstruction-2026', destination: '/tech', permanent: true },
      { source: '/bank-of-america', destination: '/news', permanent: true },
      { source: '/bio-hacking/bianca-dias-bbl-death-brazil-insurance-shift', destination: '/bio-hacking', permanent: true },
      { source: '/bio-hacking/eledon-pharmaceuticals-eldn-cd40l-tegoprubart-transplant-2026', destination: '/bio-hacking', permanent: true },
      { source: '/bio-hacking/news/oslo-patient-hiv-cure-ccr5-bone-marrow-transplant-2026', destination: '/bio-hacking', permanent: true },
      { source: '/bio-hacking/news/rockefeller-crispr-stem-cell-living-drug-factory-hiv-malaria-influenza', destination: '/bio-hacking', permanent: true },
      { source: '/bio-hacking/news/science-study-3000-genes-sex-differences-human-brain-decasien-2026', destination: '/bio-hacking', permanent: true },
      { source: '/bio-hacking/penn-study-unreported-glp-1-side-effects-reddit', destination: '/bio-hacking', permanent: true },
      { source: '/blackrock/blackrock-fidelity-bought-400m-bitcoin-golds-worst-weekly-drop', destination: '/crypto', permanent: true },
      { source: '/blackrock/news/blackrock-57-million-iqm-quantum-computers-us-listing-2026', destination: '/news', permanent: true },
      { source: '/blackrock/news/blackrock-600m-bitcoin-cold-storage-ibit-etf-settlement', destination: '/crypto', permanent: true },
      { source: '/blackrock', destination: '/news', permanent: true },
      { source: '/blitzy-ai-powered-autonomous-software-development', destination: '/tech', permanent: true },
      { source: '/blog', destination: '/news', permanent: true },
      { source: '/california/california-highway-expansion-2026-state-transportation-improvement-program', destination: '/california', permanent: true },
      { source: '/cars/2025-nissan-z-vs-toyota-gr-supra-comparison', destination: '/news', permanent: true },
      { source: '/cars/ferrari', destination: '/news', permanent: true },
      { source: '/cars/ford', destination: '/news', permanent: true },
      { source: '/cars/porsche/911-gt3-sc-sport-cabriolet-reveal-2026', destination: '/news', permanent: true },
      { source: '/cars/porsche', destination: '/news', permanent: true },
      { source: '/cars/tesla-semi-truckers-mass-production-nevada-2026', destination: '/news', permanent: true },
      { source: '/central-cee/all-roads-lead-home-march-28th-ep', destination: '/news', permanent: true },
      { source: '/claude/news/anthropic-claude-design-conversational-visual-canvas-canva-partnership', destination: '/tech', permanent: true },
      { source: '/claude/news/anthropic-claude-pro-plan-claude-code-access-2026', destination: '/tech', permanent: true },
      { source: '/claude/news/anthropic-coreweave-multiyear-data-center-deal', destination: '/tech', permanent: true },
      { source: '/claude/news/anthropic-government-id-verification-claude', destination: '/tech', permanent: true },
      { source: '/claude/news/anthropic-mythos-uk-banks-access-pip-white', destination: '/tech', permanent: true },
      { source: '/claude/news/anthropic-mythos-uk-banks-expansion', destination: '/tech', permanent: true },
      { source: '/claude/news/antrhopic-opus-3-retires', destination: '/tech', permanent: true },
      { source: '/claude/news/datatalks-course-wiped-by-claudecode', destination: '/tech', permanent: true },
      { source: '/claude/news/ecb-anthropic-claude-mythos-systemic-risk-inquiry', destination: '/tech', permanent: true },
      { source: '/claude/news/federal-agencies-replace-claude-gpt-41-trump-executive-directive', destination: '/tech', permanent: true },
      { source: '/claude/news/imf-georgieva-anthropic-mythos-financial-stability-warning', destination: '/tech', permanent: true },
      { source: '/claude/news/software-stocks-crater-anthropic-mythos-gatekeep', destination: '/tech', permanent: true },
      { source: '/claude/news/white-house-omb-federal-agencies-anthropic-mythos-access', destination: '/tech', permanent: true },
      { source: '/clothing/fabletics', destination: '/clothing', permanent: true },
      { source: '/clothing/gymshark/which-gymshark-leggings-are-best-for-lifting', destination: '/clothing/gymshark', permanent: true },
      { source: '/clothing/new-balance/energy-arc-fuelcell-supercomp', destination: '/clothing', permanent: true },
      { source: '/clothing/new-balance', destination: '/clothing', permanent: true },
      { source: '/clothing/skims/ceo', destination: '/clothing', permanent: true },
      { source: '/clothing/skims/creative-director', destination: '/clothing', permanent: true },
      { source: '/clothing/skims', destination: '/clothing', permanent: true },
      { source: '/clothing/vans', destination: '/clothing', permanent: true },
      { source: '/clothing/young-la', destination: '/clothing', permanent: true },
      { source: '/college/guides/non-degree-studies-at-university-of-texas-austin', destination: '/news', permanent: true },
      { source: '/copyright/elemental-atlus-royalties', destination: '/copyright', permanent: true },
      { source: '/copyright/meta/meta-child-safety-verdicts-new-mexico-los-angeles-march-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/meta/news/new-mexico-jury-meta-375m-consumer-protection-verdict-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/news/aoc-mlb-polymarket-gambling-warning', destination: '/copyright', permanent: true },
      { source: '/copyright/news/baltimore-xai-grok-sexual-deepfakes-lawsuit-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/news/circle-class-action-drift-protocol-285m-hack-solana', destination: '/copyright', permanent: true },
      { source: '/copyright/news/deere-99m-settlement-right-to-repair-digital-tools', destination: '/copyright', permanent: true },
      { source: '/copyright/news/detroit-first-city-oppose-prediction-markets-coinbase-lawsuit-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/news/kalshi-suspends-candidates-betting-own-races-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/news/letitia-james-sues-counter-strike', destination: '/copyright', permanent: true },
      { source: '/copyright/news/ninth-circuit-pauses-app-store-ruling-apple-supreme-court', destination: '/copyright', permanent: true },
      { source: '/copyright/news/trump-prediction-markets-cftc-van-dyke-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/nicole-daedone-sentenced-9-years-onetaste-forced-labor-2026', destination: '/copyright', permanent: true },
      { source: '/copyright/sony/playstation-age-verification-psn-online-safety-laws-2026', destination: '/copyright', permanent: true },
      { source: '/crypto/bernstein-circle-coinbase-stablecoin-kings-ai-era', destination: '/crypto', permanent: true },
      { source: '/crypto/coinbase/clarity-act-stablecoin-yield-ban', destination: '/crypto', permanent: true },
      { source: '/crypto/coinbase-new-york-ath-ray-nct-strk-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/hbar/rba-cbdc-hashsphere-hedera-project-acacia', destination: '/crypto', permanent: true },
      { source: '/crypto/news/anchorage-digital-tron-institutional-custody-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/news/anchorage-usat-expands-to-celo-network', destination: '/crypto', permanent: true },
      { source: '/crypto/news/bip-361-quantum-bitcoin-legacy-sunset', destination: '/crypto', permanent: true },
      { source: '/crypto/news/bitcoin-whale-20m-binance-large-holder-selloffs', destination: '/crypto', permanent: true },
      { source: '/crypto/news/chainlink-anchorage-blockchain-leadership-fund-pac-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/news/coinbase-armstrong-network-states-everything-exchange', destination: '/crypto', permanent: true },
      { source: '/crypto/news/fed-cbdc-halted-stablecoins-digital-dollar-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/news/florida-hb175-stablecoin-law-payment-regulation', destination: '/crypto', permanent: true },
      { source: '/crypto/news/kucoin-cftc-settlement-us-bar-peken-global', destination: '/crypto', permanent: true },
      { source: '/crypto/news/ripple-convera-stablecoin-sandwich-b2b-payments', destination: '/crypto', permanent: true },
      { source: '/crypto/news/tether-fasset-gold-visa-card-xaut-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/news/tether-qvac-sdk-on-device-ai-cloud-monopoly', destination: '/crypto', permanent: true },
      { source: '/crypto/news/visa-usdc-solana-settlement-lead-bank-cross-river', destination: '/crypto', permanent: true },
      { source: '/crypto/trump/meme-coin-gala-whca-shooting-sanders-4b-kleptocracy-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/usdc/circle-mints-750m-on-solana-network', destination: '/crypto', permanent: true },
      { source: '/crypto/usdc/circle-unfreeze-wallets-zachxbt-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/usdc/news/circle-usdc-drift-hack-285m-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/usdc', destination: '/crypto', permanent: true },
      { source: '/crypto/warren-mrbeast-step-crypto-children', destination: '/crypto', permanent: true },
      { source: '/crypto/white-house-block-and-find-out-coinbase-clarity-act-2026', destination: '/crypto', permanent: true },
      { source: '/crypto/xrp/80b-ledger-exploit-confirmed-by-ceo', destination: '/crypto', permanent: true },
      { source: '/crypto/xrp', destination: '/crypto', permanent: true },
      { source: '/cuba/news/cuban-border-guards-kill-four-florida-speedboat-cayo-falcones', destination: '/news', permanent: true },
      { source: '/define/agentic-ai', destination: '/tech', permanent: true },
      { source: '/define/bets-off-act', destination: '/news', permanent: true },
      { source: '/define/comet-ai-web-browser-vs-atlas-by-chatgpt', destination: '/comet-ai-web-browser-vs-atlas-by-chatgpt', permanent: true },
      { source: '/define/crypto/tether', destination: '/crypto', permanent: true },
      { source: '/define/crypto/txc-stablecoin', destination: '/crypto', permanent: true },
      { source: '/define/democrate/dhs-funding-shutdown-senate-democrats-counteroffer-march-2026', destination: '/news', permanent: true },
      { source: '/define/difference-between-http-and-rest-api-servers', destination: '/tech', permanent: true },
      { source: '/define/hedera-vs-solana-for-dapps', destination: '/crypto', permanent: true },
      { source: '/define/how-do-prediction-markets-work', destination: '/news', permanent: true },
      { source: '/define/largest-prediction-markets-united-states-2026', destination: '/news', permanent: true },
      { source: '/define/malware/axios-npm-hijacked-rat-malware', destination: '/tech', permanent: true },
      { source: '/define/malware/deepload-ai-obfuscation-clickfix-2026', destination: '/tech', permanent: true },
      { source: '/define/model-context-protocol', destination: '/tech', permanent: true },
      { source: '/define/most-important-stablecoins-world-2026', destination: '/crypto', permanent: true },
      { source: '/define/nestjs-vs-nextjs-express', destination: '/tech', permanent: true },
      { source: '/define/openai-hires-openclaw-creator-peter-steinberger-foundation', destination: '/open-ai', permanent: true },
      { source: '/define/prediction-market/:path*', destination: '/news', permanent: true },
      { source: '/define/proof-of-engagement-blockchain-vs-proof-of-authority', destination: '/crypto', permanent: true },
      { source: '/define/tariff', destination: '/news', permanent: true },
      { source: '/define/vibe-coding', destination: '/tech', permanent: true },
      { source: '/define/what-is-a-smart-contract', destination: '/crypto', permanent: true },
      { source: '/define/what-is-a-stablecoin', destination: '/crypto', permanent: true },
      { source: '/define/what-is-an-llm', destination: '/tech', permanent: true },
      { source: '/define/what-is-bitcoin-halving', destination: '/crypto', permanent: true },
      { source: '/define/what-is-defi', destination: '/crypto', permanent: true },
      { source: '/define/what-is-esports', destination: '/video-games', permanent: true },
      { source: '/disney/josh-damaro', destination: '/disney', permanent: true },
      { source: '/disney/news/:path*', destination: '/disney', permanent: true },
      { source: '/earth/news/:path*', destination: '/news', permanent: true },
      { source: '/earth/:path*', destination: '/news', permanent: true },
      { source: '/editorial-standards/authors', destination: '/editorial-standards', permanent: true },
      { source: '/elon-musk/boring-company/news/:path*', destination: '/elon-musk/boring-company', permanent: true },
      { source: '/elon-musk/news/:path*', destination: '/elon-musk', permanent: true },
      { source: '/elon-musk/spacex', destination: '/elon-musk', permanent: true },
      { source: '/elon-musk/spacex-xai-merger-1-75-trillion-ipo-orbital-ai-2026', destination: '/elon-musk', permanent: true },
      { source: '/elon-musk/sun-shading-the-billionaire-wants-ai-satellites-to-block-the-sun', destination: '/elon-musk', permanent: true },
      { source: '/entertainment/apple-tv/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/beastgames/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/beastgames', destination: '/entertainment', permanent: true },
      { source: '/entertainment/hbo-max/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/hbomax', destination: '/entertainment', permanent: true },
      { source: '/entertainment/hulu', destination: '/entertainment', permanent: true },
      { source: '/entertainment/james-cameron', destination: '/entertainment', permanent: true },
      { source: '/entertainment/marvel/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/movies/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/netflix', destination: '/entertainment', permanent: true },
      { source: '/entertainment/news/:path*', destination: '/entertainment', permanent: true },
      { source: '/entertainment/survivor', destination: '/entertainment', permanent: true },
      { source: '/equipment/:path*', destination: '/news', permanent: true },
      { source: '/events/ceraweek-2026', destination: '/news', permanent: true },
      { source: '/events/davos/:path+', destination: '/events/davos', permanent: true },
      { source: '/events/gdc-2026/:path*', destination: '/news', permanent: true },
      { source: '/events/gdc-2026', destination: '/news', permanent: true },
      { source: '/events/gtc-2026/:path*', destination: '/news', permanent: true },
      { source: '/events/gtc-2026', destination: '/news', permanent: true },
      { source: '/events/news/:path*', destination: '/news', permanent: true },
      { source: '/events/starbucks/:path*', destination: '/news', permanent: true },
      { source: '/events/sxsw', destination: '/news', permanent: true },
      { source: '/finance/:path+', destination: '/news', permanent: true },
      // /finance now has its own hub page — no redirect needed
      { source: '/formula-1/:path*', destination: '/news', permanent: true },
      { source: '/get-help/:path+', destination: '/get-help', permanent: true },
      { source: '/github/news/:path*', destination: '/github', permanent: true },
      { source: '/google/agentic-vision/:path*', destination: '/google', permanent: true },
      { source: '/google/news/apple-gemini-siri-upgrade-march-2026', destination: '/google', permanent: true },
      { source: '/google/waymo/ntsb-investigation-school-bus-violations', destination: '/google', permanent: true },
      { source: '/history', destination: '/news', permanent: true },
      { source: '/index', destination: '/news', permanent: true },
      { source: '/indonesia/:path*', destination: '/news', permanent: true },
      { source: '/influencer/abby-berner', destination: '/influencer', permanent: true },
      { source: '/influencer/alanforze/:path*', destination: '/influencer', permanent: true },
      { source: '/influencer/alix-earle', destination: '/influencer', permanent: true },
      { source: '/influencer/bryson-dechambeau/:path*', destination: '/influencer', permanent: true },
      { source: '/influencer/bryson-dechambeau', destination: '/influencer', permanent: true },
      { source: '/influencer/bufalika', destination: '/influencer', permanent: true },
      { source: '/influencer/charli-damelio', destination: '/influencer', permanent: true },
      { source: '/influencer/colleen-sheehan', destination: '/influencer', permanent: true },
      { source: '/influencer/emma-chamberlain', destination: '/influencer', permanent: true },
      { source: '/influencer/iman-gadzhi', destination: '/influencer', permanent: true },
      { source: '/influencer/leah-davies', destination: '/influencer', permanent: true },
      { source: '/influencer/lean-beef-patty', destination: '/influencer', permanent: true },
      { source: '/influencer/megan-marie', destination: '/influencer', permanent: true },
      { source: '/influencer/mika-lafuente', destination: '/influencer', permanent: true },
      { source: '/influencer/miranda-marie', destination: '/influencer', permanent: true },
      { source: '/influencer/mrbeast/:path*', destination: '/influencer', permanent: true },
      { source: '/influencer/mrbeast', destination: '/influencer', permanent: true },
      { source: '/influencer/mrbeast-launches-beast-games-season-2-casting', destination: '/influencer', permanent: true },
      { source: '/influencer/news/:path*', destination: '/influencer', permanent: true },
      { source: '/influencer/nick-shirley', destination: '/influencer', permanent: true },
      { source: '/influencer/of/mikaela-testa', destination: '/influencer', permanent: true },
      { source: '/influencer/pokimane', destination: '/influencer', permanent: true },
      { source: '/influencer/serge-gatari/:path*', destination: '/influencer', permanent: true },
      { source: '/influencer/sssniperwolf', destination: '/influencer', permanent: true },
      { source: '/influencer/tren-twins', destination: '/influencer', permanent: true },
      { source: '/influencer/valkyrae', destination: '/influencer', permanent: true },
      { source: '/influencer/yellz0', destination: '/influencer', permanent: true },
      { source: '/intel/news/:path*', destination: '/intel', permanent: true },
      { source: '/investigations/:path*', destination: '/news', permanent: true },
      { source: '/ironspring-ventures-startups-are-changing-construction-goodship-track3d-fleetpulse', destination: '/news', permanent: true },
      { source: '/jackarticle/test', destination: '/news', permanent: true },
      { source: '/lawsuit/:path*', destination: '/news', permanent: true },
      { source: '/meta/:path*', destination: '/news', permanent: true },
      { source: '/meta', destination: '/news', permanent: true },
      { source: '/microsoft/xbox', destination: '/microsoft', permanent: true },
      { source: '/missing-persons', destination: '/news', permanent: true },
      { source: '/mls/:path*', destination: '/news', permanent: true },
      { source: '/nasa/europa/:path*', destination: '/nasa', permanent: true },
      { source: '/netflix/news/:path*', destination: '/news', permanent: true },
      { source: '/neurophos-ai-hardware-startup', destination: '/news', permanent: true },
      { source: '/news/2025/:path*', destination: '/news', permanent: true },
      { source: '/news/ai', destination: '/news', permanent: true },
      { source: '/news/alibaba-ai-agent-mined-crypto-during-training', destination: '/news', permanent: true },
      { source: '/news/artemis-ii-launch-lunar-journey-april-2026', destination: '/news', permanent: true },
      { source: '/news/canada/:path*', destination: '/news', permanent: true },
      { source: '/news/doordash-snap-ebt', destination: '/news', permanent: true },
      { source: '/news/iran', destination: '/news', permanent: true },
      { source: '/news/layoffs/:path*', destination: '/news', permanent: true },
      { source: '/news/newyork/:path*', destination: '/news', permanent: true },
      { source: '/news/texas/:path*', destination: '/news', permanent: true },
      { source: '/news/world/:path*', destination: '/news', permanent: true },
      { source: '/newsarticle/test', destination: '/news', permanent: true },
      { source: '/ngos/:path*', destination: '/news', permanent: true },
      { source: '/objectwire', destination: '/news', permanent: true },
      { source: '/open-ai/news/:path*', destination: '/open-ai', permanent: true },
      { source: '/podcasts/:path*', destination: '/news', permanent: true },
      { source: '/politics/news/:path*', destination: '/news', permanent: true },
      { source: '/profile/[username]', destination: '/profile', permanent: true },
      { source: '/redbull/news/:path*', destination: '/redbull', permanent: true },
      { source: '/research', destination: '/news', permanent: true },
      { source: '/rocket-league', destination: '/news', permanent: true },
      { source: '/saas/apptronik', destination: '/saas', permanent: true },
      { source: '/saas/cognyte', destination: '/saas', permanent: true },
      { source: '/saas/gatik', destination: '/saas', permanent: true },
      { source: '/saas/general-motors', destination: '/saas', permanent: true },
      { source: '/saas/novartis', destination: '/saas', permanent: true },
      { source: '/saas/sailpoint', destination: '/saas', permanent: true },
      { source: '/saas/upside', destination: '/saas', permanent: true },
      { source: '/search/mozilla-firefox', destination: '/search', permanent: true },
      { source: '/service/:path*', destination: '/austin-private-detective-agency', permanent: true },
      { source: '/service', destination: '/austin-private-detective-agency', permanent: true },
      { source: '/social/news/:path*', destination: '/social', permanent: true },
      { source: '/social/tiktok/:path*', destination: '/social', permanent: true },
      { source: '/tags/[tag]', destination: '/tags', permanent: true },
      { source: '/team', destination: '/news', permanent: true },
      { source: '/tech/deepseek/:path*', destination: '/tech', permanent: true },
      { source: '/tech/digital-realty/:path*', destination: '/tech', permanent: true },
      { source: '/tech/newegg/:path*', destination: '/tech', permanent: true },
      { source: '/tech/oracle', destination: '/tech', permanent: true },
      { source: '/tech/real-estate', destination: '/tech', permanent: true },
      { source: '/tech/square/:path*', destination: '/tech', permanent: true },
      { source: '/tech/stripe/:path*', destination: '/tech', permanent: true },
      { source: '/technology/ai-sovereignty-shift', destination: '/technology', permanent: true },
      { source: '/technology/alibaba', destination: '/technology', permanent: true },
      { source: '/technology/articles/:path*', destination: '/technology', permanent: true },
      { source: '/technology/news/:path*', destination: '/technology', permanent: true },
      { source: '/technology/stablecoins/:path*', destination: '/technology', permanent: true },
      { source: '/technology/stablecoins', destination: '/technology', permanent: true },
      { source: '/technology/terrapower/:path*', destination: '/technology', permanent: true },
      { source: '/tiktok', destination: '/news', permanent: true },
      { source: '/tiktok/:path*', destination: '/news', permanent: true },
      { source: '/trump/china/:path*', destination: '/trump', permanent: true },
      { source: '/trump/kristi-noem/:path*', destination: '/trump', permanent: true },
      { source: '/trump/kristi-noem', destination: '/trump', permanent: true },
      { source: '/trump/news/:path*', destination: '/trump', permanent: true },
      { source: '/video-games/007-first-light/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/007-first-light', destination: '/video-games', permanent: true },
      { source: '/video-games/Digital-Foundry', destination: '/video-games', permanent: true },
      { source: '/video-games/anime/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/ark-raiders/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/ark-raiders', destination: '/video-games', permanent: true },
      { source: '/video-games/battlefield-6/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/bellwright', destination: '/video-games', permanent: true },
      { source: '/video-games/capcom/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/capcom', destination: '/video-games', permanent: true },
      { source: '/video-games/dragon-ball/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/epic/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/fortnite/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/fortnite', destination: '/video-games', permanent: true },
      { source: '/video-games/forza-horizon-6/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/forza-horizon-6', destination: '/video-games', permanent: true },
      { source: '/video-games/gamestop/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/gta-6/:path+', destination: '/video-games/gta-6', permanent: true },
      { source: '/video-games/mario-kart/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/marvels-wolverine', destination: '/video-games', permanent: true },
      { source: '/video-games/mha/alls-justice', destination: '/video-games', permanent: true },
      { source: '/video-games/mha', destination: '/video-games', permanent: true },
      { source: '/video-games/mha/ultra-rumble', destination: '/video-games', permanent: true },
      { source: '/video-games/mha/ultra-rumble/season-15/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/mha/ultra-rumble/season-15', destination: '/video-games', permanent: true },
      { source: '/video-games/mha/ultra-rumble/season-16/cluster-bakugo', destination: '/video-games/mha/ultra-rumble/season-16', permanent: true },
      { source: '/video-games/mythmatch', destination: '/video-games', permanent: true },
      { source: '/video-games/new/crimson-desert/:path+', destination: '/video-games/new/crimson-desert', permanent: true },
      { source: '/video-games/new/slay-the-spire-2', destination: '/video-games', permanent: true },
      { source: '/video-games/new/windrose/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/new/windrose', destination: '/video-games', permanent: true },
      { source: '/video-games/news/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/pokemon/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/racing/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/rainbow-6-siege', destination: '/video-games', permanent: true },
      { source: '/video-games/resident-evil-requiem/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/resident-evil-requiem', destination: '/video-games', permanent: true },
      { source: '/video-games/star-wars/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/switch2/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/toxic-comando', destination: '/video-games', permanent: true },
      { source: '/video-games/ubisoft', destination: '/video-games', permanent: true },
      { source: '/video-games/unreal-engine/:path*', destination: '/video-games', permanent: true },
      { source: '/video-games/valve-corporation/:path+', destination: '/video-games/valve-corporation', permanent: true },
      { source: '/video-games/windrose/:path*', destination: '/video-games', permanent: true },
      { source: '/winter-olympics/:path*', destination: '/news', permanent: true },
      { source: '/winter-olympics', destination: '/news', permanent: true },
      { source: '/world-cup/:path*', destination: '/news', permanent: true },
      { source: '/wwe/:path*', destination: '/news', permanent: true },
      { source: '/wwe', destination: '/news', permanent: true },
      { source: '/youtube/mat-armstrong/:path*', destination: '/youtube', permanent: true },
      { source: '/youtube/mat-armstrong', destination: '/youtube', permanent: true },
      { source: '/youtube/nelk-boys', destination: '/youtube', permanent: true },
      { source: '/youtube/news/:path*', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/arthur-tv', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/behzinga', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/charity-match/england-vs-france-2026', destination: '/youtube/sidemen/charity-match', permanent: true },
      { source: '/youtube/sidemen/george-clark', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/ksi/:path*', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/ksi', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/miniminter', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/news', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/vikkstar', destination: '/youtube', permanent: true },
      { source: '/youtube/sidemen/w2s', destination: '/youtube', permanent: true },

      // ── Non-ranking GSC cleanup (Table.csv May 2026) ──
  { source: '/tags/nonprofits', destination: '/news', permanent: true },
  { source: '/tags/bianca-dias-bbl-death-brazil-insurance-shift', destination: '/news', permanent: true },
  { source: '/tags/fabletics', destination: '/news', permanent: true },
  { source: '/tags/nvidia', destination: '/news', permanent: true },
  { source: '/influencer/news/logan-paul-sells-pokemon-card-16-million', destination: '/influencer', permanent: true },
  { source: '/tags/007-first-light', destination: '/news', permanent: true },
  { source: '/tags/alphabet-inc-the-history-of-google', destination: '/news', permanent: true },
  { source: '/tags/gpu-interconnect', destination: '/news', permanent: true },
  { source: '/tags/racing', destination: '/news', permanent: true },
  { source: '/youtube/sidemen/ksi/dagenham-redbridge', destination: '/youtube', permanent: true },
  { source: '/tags/sidemen', destination: '/news', permanent: true },
  { source: '/tags/cloudflare', destination: '/news', permanent: true },
  { source: '/tags/first-ai-insurance-apps', destination: '/news', permanent: true },
  { source: '/video-games/anime/hunter-hunter-nen-survivor', destination: '/video-games', permanent: true },
  { source: '/winter-olympics/slovenia/domen-prevc', destination: '/winter-olympics', permanent: true },
  { source: '/influencer/kirstentoosweet', destination: '/influencer', permanent: true },
  { source: '/tags/pentagon', destination: '/news', permanent: true },
  { source: '/tags/asset-collection', destination: '/news', permanent: true },
  { source: '/tags/affordability', destination: '/news', permanent: true },
  { source: '/tags/f1', destination: '/news', permanent: true },
  { source: '/tags/national-security', destination: '/news', permanent: true },
  { source: '/tags/sam-altman', destination: '/news', permanent: true },
  { source: '/tags/non-league-football', destination: '/news', permanent: true },
  { source: '/tags/sam-altman-visits-hedera-team', destination: '/news', permanent: true },
  { source: '/tags/rockstar-gta6-psn-profile-exploit', destination: '/news', permanent: true },
  { source: '/tags/alls-justice', destination: '/news', permanent: true },
  { source: '/winter-olympics/austria/janine-flock', destination: '/winter-olympics', permanent: true },
  { source: '/video-games/news/rocket-league-season-22-v2-66-patch-notes', destination: '/video-games', permanent: true },
  { source: '/video-games/anime/seven-deadly-sins-origin', destination: '/video-games', permanent: true },
  { source: '/tags/oftebro-second-nordic-combined-gold', destination: '/news', permanent: true },
  { source: '/tags/polyphony-digital', destination: '/news', permanent: true },
  { source: '/tags/serge-gatari', destination: '/news', permanent: true },
  { source: '/tags/nyse-ma', destination: '/news', permanent: true },
  { source: '/tags/boxing', destination: '/news', permanent: true },
  { source: '/tags/china-japan-standoff-2026', destination: '/news', permanent: true },
  { source: '/tags/falcon', destination: '/news', permanent: true },
  { source: '/formula-1/stefano-domenicali', destination: '/formula-1', permanent: true },
  { source: '/tags/stablecoins', destination: '/news', permanent: true },
  { source: '/tags/valve-ships-cs2-animation-overhaul-not-cs3-april-2026', destination: '/news', permanent: true },
  { source: '/tags/ken-jennings', destination: '/news', permanent: true },
  { source: '/microsoft/news/xbox-co-creator-microsoft-sunsetting-gaming-ai', destination: '/microsoft', permanent: true },
  { source: '/tags/moon', destination: '/news', permanent: true },
  { source: '/tags/arknights-endfield', destination: '/news', permanent: true },
  { source: '/tags/johannes-klaebo', destination: '/news', permanent: true },
  { source: '/tags/definitions', destination: '/news', permanent: true },
  { source: '/tags/austin-tech-hub-decline', destination: '/news', permanent: true },
  { source: '/tags/gpu', destination: '/news', permanent: true },
  { source: '/tags/txc-stablecoin', destination: '/news', permanent: true },
  { source: '/tags/battle-royale', destination: '/news', permanent: true },
  { source: '/tags/gta-6-pre-orders-playstation-store-database-update-march-2026', destination: '/news', permanent: true },
  { source: '/tags/formula-1', destination: '/news', permanent: true },
  { source: '/tags/tokenization', destination: '/news', permanent: true },
  { source: '/tags/yellz0', destination: '/news', permanent: true },
  { source: '/tags/xaut', destination: '/news', permanent: true },
  { source: '/tags/apple-google-gemini-partnership', destination: '/news', permanent: true },
  { source: '/tags/dc-comics', destination: '/news', permanent: true },
  { source: '/tags/asml-hutto-semiconductor', destination: '/news', permanent: true },
  { source: '/tags/spacex', destination: '/news', permanent: true },
  { source: '/tags/star-wars', destination: '/news', permanent: true },
  { source: '/tags/investigations', destination: '/news', permanent: true },
  { source: '/tags/ethan-payne', destination: '/news', permanent: true },
  { source: '/tags/middle-east', destination: '/news', permanent: true },
  { source: '/tags/mha', destination: '/news', permanent: true },
  { source: '/tags/corrections', destination: '/news', permanent: true },
  { source: '/tags/georgia', destination: '/news', permanent: true },
  { source: '/tags/azure', destination: '/news', permanent: true },
  { source: '/tags/claude-sonnet-4.6', destination: '/news', permanent: true },
  { source: '/tags/marvel', destination: '/news', permanent: true },
  { source: '/tags/blog', destination: '/news', permanent: true },
  { source: '/tags/josh-damaro', destination: '/news', permanent: true },
  { source: '/youtube/sidemen/chippo-grimes', destination: '/youtube', permanent: true },
  { source: '/technology/alibaba/wukong-ai-agent-enterprise-platform-march-2026', destination: '/technology', permanent: true },
  { source: '/tags/luca-spechenhauser', destination: '/news', permanent: true },
  { source: '/tags/intel', destination: '/news', permanent: true },
  { source: '/tags/hulu', destination: '/news', permanent: true },
  { source: '/tags/ilia-malinin', destination: '/news', permanent: true },
  { source: '/video-games/007-first-light/news/lenny-kravitz-bawma-cinematic-ign-fan-fest', destination: '/video-games', permanent: true },
  { source: '/tags/alysa-liu', destination: '/news', permanent: true },
  { source: '/tags/epic', destination: '/news', permanent: true },
  { source: '/tech/alphafold-protein-complex-structures-database-2026', destination: '/tech', permanent: true },
  { source: '/tags/hbo', destination: '/news', permanent: true },
  { source: '/tags/jason', destination: '/news', permanent: true },
  { source: '/tags/about', destination: '/news', permanent: true },
  { source: '/tech/perplexity/news/perplexity-computer-agentic-ai-platform-explained-2026', destination: '/tech', permanent: true },
  { source: '/tags/dragon-ball', destination: '/news', permanent: true },
  { source: '/tags/trade', destination: '/news', permanent: true },
  { source: '/tags/biathlon-relay-gold-perrot-2026', destination: '/news', permanent: true },
  { source: '/winter-olympics/usa/darryl-payne-jr', destination: '/winter-olympics', permanent: true },
  { source: '/tags/sora', destination: '/news', permanent: true },
  { source: '/tags/instagram', destination: '/news', permanent: true },
  { source: '/cursor/automations-event-driven-ai-coding', destination: '/cursor', permanent: true },
  { source: '/tags/card-networks', destination: '/news', permanent: true },
  { source: '/tags/grok-xai-pentagon-classified-approval-federal-safety-warnings-2026', destination: '/news', permanent: true },
  { source: '/tags/ai-data-centers', destination: '/news', permanent: true },
  { source: '/tags/minesoda', destination: '/news', permanent: true },
  { source: '/tags/qualcomm-nvidia-6g-coalitions-mwc-2026', destination: '/news', permanent: true },
  { source: '/tags/copyright', destination: '/news', permanent: true },
  { source: '/trump/news/trump-administration-10-billion-fee-tiktok-deal', destination: '/trump', permanent: true },
  { source: '/social/meta/news/meta-targeted-layoffs-reality-labs-social-teams-march-2026', destination: '/social', permanent: true },
  { source: '/winter-olympics/usa/jordan-stolz', destination: '/winter-olympics', permanent: true },
  { source: '/tags/test', destination: '/news', permanent: true },
  { source: '/microsoft/news/apple-five-new-products-march-2026', destination: '/microsoft', permanent: true },
  { source: '/entertainment/news/jack-ryan-ghost-war-trailer-prime-video-2026', destination: '/entertainment', permanent: true },
  { source: '/events/gdc-2026/valve-steam-machine-steam-frame-compatibility-gdc-2026', destination: '/events', permanent: true },
  { source: '/influencer/alanforze/supernova-genesis-2026-netflix-arena-ciudad-de-mexico', destination: '/influencer', permanent: true },
  { source: '/tags/apple-gemini-siri-upgrade-march-2026', destination: '/news', permanent: true },
  { source: '/influencer/eden-gross', destination: '/influencer', permanent: true },
  { source: '/tags/pirate', destination: '/news', permanent: true },
  { source: '/tags/terms', destination: '/news', permanent: true },
  { source: '/tags/pokopia', destination: '/news', permanent: true },
  { source: '/tiktok/seedance-2.0', destination: '/tiktok', permanent: true },
  { source: '/tags/ai', destination: '/news', permanent: true },
  { source: '/get-help/contact', destination: '/news', permanent: true },
  { source: '/trump/news/trump-ai-kill-switch-mythos-regulators', destination: '/trump', permanent: true },
  { source: '/video-games/nintendo/google-project-genie-ai-knockoffs', destination: '/video-games', permanent: true },
  { source: '/google/ai-coding-strike-team-antigravity-claude-code-2026', destination: '/google', permanent: true },
  { source: '/tags/xai', destination: '/news', permanent: true },
  { source: '/intel/news/intel-joins-musk-terafab-ai-chip-project-texas', destination: '/intel', permanent: true },
  { source: '/tags/skims', destination: '/news', permanent: true },
  { source: '/tags/acquisition', destination: '/news', permanent: true },
  { source: '/video-games/switch2/super-mario-wonder-switch2-edition-bellabel-park', destination: '/video-games', permanent: true },
  { source: '/tags/general-motors', destination: '/news', permanent: true },
  { source: '/tags/ai-agent', destination: '/news', permanent: true },
  { source: '/entertainment/hbo-max/harry-potter-series-unprecedented-financial-commitment-hbo', destination: '/entertainment', permanent: true },
  { source: '/open-ai/news/world-worldcoin-tools-for-humanity-deep-face-tinder-zoom-docusign-human-id', destination: '/open-ai', permanent: true },
  { source: '/tags/star-wars-zero-company', destination: '/news', permanent: true },
  { source: '/world-cup/news/fifa-world-cup-2026-final-halftime-show-chris-martin', destination: '/world-cup', permanent: true },
  { source: '/tags/italy', destination: '/news', permanent: true },
  { source: '/video-games/news/arc-raiders-discord-plaintext-security', destination: '/video-games', permanent: true },
  { source: '/finance/news/charles-schwab-prediction-markets-rick-wurster-2026', destination: '/finance', permanent: true },
  { source: '/youtube/chicos-toxicos/sava-schultz', destination: '/youtube', permanent: true },
  { source: '/tags/premier-league', destination: '/news', permanent: true },
  { source: '/authors/jack-sterling', destination: '/authors', permanent: true },
  { source: '/tech/anthropic-private-equity-10-billion-blackstone-joint-venture-2026', destination: '/tech', permanent: true },
  { source: '/video-games/switch2/pokemon-pokopia', destination: '/video-games', permanent: true },
  { source: '/nvidia/news/blackwell-b300-vs-amd-mi300x-vs-google-tpu-v6-2026-benchmark', destination: '/nvidia', permanent: true },
  { source: '/tags/steve-will-do-it-kicked-of-logan-paul-s-podcast-making-an-official-return-to-youtube', destination: '/news', permanent: true },
  { source: '/microsoft/news/project-helix-xbox-pc-hybrid-console', destination: '/microsoft', permanent: true },
  { source: '/video-games/news/outersloth-rejects-ai', destination: '/video-games', permanent: true },
  { source: '/tags/security', destination: '/news', permanent: true },
  { source: '/tags/wukong-ai-agent-enterprise-platform-march-2026', destination: '/news', permanent: true },
  { source: '/video-games/nintendo/donkey-kong-bananza', destination: '/video-games', permanent: true },
  { source: '/news/ubc-crispr-topical-gene-therapy-skin', destination: '/news', permanent: true },
  { source: '/tags/jordan-stolz', destination: '/news', permanent: true },
  { source: '/tags/swiss-skier-von-allmen-wins-third-gold', destination: '/news', permanent: true },
  { source: '/tags/sandfall-interactive', destination: '/news', permanent: true },
  { source: '/tags/hbar', destination: '/news', permanent: true },
  { source: '/tags/cognyte', destination: '/news', permanent: true },
  { source: '/google/news/gemini-embedding-2-multimodal-embedding-model', destination: '/google', permanent: true },
  { source: '/meta/news/meta-poaches-thinking-machines-lab-founders-mira-murati-2026', destination: '/meta', permanent: true },
  { source: '/tags/american-express', destination: '/news', permanent: true },
  { source: '/tags/beast-games', destination: '/news', permanent: true },
  { source: '/influencer/diamond-gym', destination: '/influencer', permanent: true },
  { source: '/meta/news/meta-broadcom-mtia-chip-partnership-2029-hock-tan', destination: '/meta', permanent: true },
  { source: '/tags/fifa-backs-mexico-after-cartel-violence-jalisco', destination: '/news', permanent: true },
  { source: '/define/prediction-market/binance-launches-prediction-market', destination: '/define', permanent: true },
  { source: '/tags/shopify-agentic-storefronts-chatgpt-default-march-2026', destination: '/news', permanent: true },
  { source: '/google/news/google-deepmind-claude-code-steve-yegge-demis-hassabis-2026', destination: '/google', permanent: true },
  { source: '/open-ai/news/symphony-open-source-autonomous-coding-agents', destination: '/open-ai', permanent: true },
  { source: '/tags/daddywellness', destination: '/news', permanent: true },
  { source: '/tags/dispatch-adhoc-studio', destination: '/news', permanent: true },
  { source: '/tags/alphafold-protein-complex-structures-database-2026', destination: '/news', permanent: true },
  { source: '/tags/w2s', destination: '/news', permanent: true },
  { source: '/trump/god-squad-gulf-drilling-esa-exemption', destination: '/trump', permanent: true },
  { source: '/influencer/ari-kytsya', destination: '/influencer', permanent: true },
  { source: '/tags/saas', destination: '/news', permanent: true },
  { source: '/tags/class-action-jensen-huang-crypto-revenue-2026', destination: '/news', permanent: true },
  { source: '/tags/payments', destination: '/news', permanent: true },
  { source: '/tags/apple-podcasts', destination: '/news', permanent: true },
  { source: '/tags/ai-course-review', destination: '/news', permanent: true },
  { source: '/tags/survivor', destination: '/news', permanent: true },
  { source: '/tags/analysis', destination: '/news', permanent: true },
  { source: '/tags/disney', destination: '/news', permanent: true },
  { source: '/winter-olympics/norway/johannes-klaebo', destination: '/winter-olympics', permanent: true },
  { source: '/tags/my-hero-ultra-rumble', destination: '/news', permanent: true },
  { source: '/tags/starlink-economic-analysis', destination: '/news', permanent: true },
  { source: '/tags/doordash-snap-ebt', destination: '/news', permanent: true },
  { source: '/tags/dawn-of-orbital-ai', destination: '/news', permanent: true },
  { source: '/tags/music', destination: '/news', permanent: true },
  { source: '/tags/usa', destination: '/news', permanent: true },
  { source: '/tags/usdt', destination: '/news', permanent: true },
  { source: '/nvidia/news/nvidia-engineer-inference-budget-token-salary-gtc-2026', destination: '/nvidia', permanent: true },
  { source: '/tags/mrbeast-launches-beast-games-season-2-casting', destination: '/news', permanent: true },
  { source: '/influencer/daddywellness', destination: '/influencer', permanent: true },
  { source: '/tags/neverness-to-everness', destination: '/news', permanent: true },
  { source: '/tags/epic-games-sues-fortnite-leaks-contractor', destination: '/news', permanent: true },
  { source: '/tags/flash-point-update', destination: '/news', permanent: true },
  { source: '/winter-olympics/usa/team-usa-wins-five-medals-across-five-sports', destination: '/winter-olympics', permanent: true },
  { source: '/youtube/sidemen/charity-match-results-2026', destination: '/youtube', permanent: true },
  { source: '/news/texas/lifetime-fitness-austin-new-location-opening-in-2025-november-1301-south-lamar', destination: '/news', permanent: true },
  { source: '/tags/jack-wang', destination: '/news', permanent: true },
  { source: '/tags/winter-olympics', destination: '/news', permanent: true },
  { source: '/tags/contractor', destination: '/news', permanent: true },
  { source: '/tags/announcement-from-the-new-tiktok-usds-joint-venture-llc', destination: '/news', permanent: true },
  { source: '/tags/mrbeast', destination: '/news', permanent: true },
  { source: '/tags/creative-director', destination: '/news', permanent: true },
  { source: '/tags/fortnite', destination: '/news', permanent: true },
  { source: '/tags/omnibus-project', destination: '/news', permanent: true },
  { source: '/tags/xrp', destination: '/news', permanent: true },
  { source: '/tags/tv', destination: '/news', permanent: true },
  { source: '/tags/life-biosciences-fda-clearance-epigenetic-reprogramming-er-100', destination: '/news', permanent: true },
  { source: '/tags/defi', destination: '/news', permanent: true },
  { source: '/influencer/diamond-gym/prime', destination: '/influencer', permanent: true },
  { source: '/winter-olympics/usa/hannah-bilka', destination: '/winter-olympics', permanent: true },
  { source: '/tags/earth', destination: '/news', permanent: true },
  { source: '/tags/largest-prediction-markets-united-states-2026', destination: '/news', permanent: true },
  { source: '/trump/trump-totalenergies-928m-offshore-wind-exit', destination: '/trump', permanent: true },
  { source: '/tags/charity-match', destination: '/news', permanent: true },
  { source: '/tags/web3', destination: '/news', permanent: true },
  { source: '/tags/vans', destination: '/news', permanent: true },
  { source: '/tags/fintech', destination: '/news', permanent: true },
  { source: '/tags/open-world', destination: '/news', permanent: true },
  { source: '/tags/eledon-pharmaceuticals-cd40l-pathway-therapies', destination: '/news', permanent: true },
  { source: '/tags/ultra-rumble', destination: '/news', permanent: true },
  { source: '/tags/emergency-surgery-after-crash', destination: '/news', permanent: true },
  { source: '/tags/2025', destination: '/news', permanent: true },
  { source: '/tags/elixir', destination: '/news', permanent: true },
  { source: '/tags/netflix', destination: '/news', permanent: true },
  { source: '/tags/influencer', destination: '/news', permanent: true },
  { source: '/tags/cuba', destination: '/news', permanent: true },
  { source: '/tech/news/gaming-industry-layoffs-ea-sony-riot-ubisoft-february-2026', destination: '/tech', permanent: true },
  { source: '/tags/nvidia-engineer-inference-budget-token-salary-gtc-2026', destination: '/news', permanent: true },
  { source: '/tags/pearl-abyss', destination: '/news', permanent: true },
  { source: '/tags/indie-devs-dlss5-boycott-new-blood-interactive', destination: '/news', permanent: true },
  { source: '/tags/cars', destination: '/news', permanent: true },
  { source: '/tags/valve-corporation', destination: '/news', permanent: true },
  { source: '/tags/chips', destination: '/news', permanent: true },
  { source: '/video-games/new/windrose/release-date-holdoff', destination: '/video-games', permanent: true },
  { source: '/news/alibaba-qwen-3-6-model-preview-responses-api-typescript-sdk-2026', destination: '/news', permanent: true },
  { source: '/tags/warner-bros.-discovery', destination: '/news', permanent: true },
  { source: '/tags/rocket-league-season-22-v2-66-patch-notes', destination: '/news', permanent: true },
  { source: '/events/news/github-universe-october-28th-and-29th-san-francisco', destination: '/events', permanent: true },
  { source: '/influencer/serge-gatari', destination: '/influencer', permanent: true },
  { source: '/artists/yeat', destination: '/artists', permanent: true },
  { source: '/tags/bitcoin', destination: '/news', permanent: true },
  { source: '/tags/roguelike', destination: '/news', permanent: true },
  { source: '/tags/surveillance', destination: '/news', permanent: true },
  { source: '/winter-olympics/georgia/first-winter-olympic-medal-figure-skating', destination: '/winter-olympics', permanent: true },
  { source: '/tags/social-media', destination: '/news', permanent: true },
  { source: '/tags/kaiser-permanente-ufcw-contract-ai-protections-2026', destination: '/news', permanent: true },
  { source: '/define/hetzner-cloud-vs-digitalocean', destination: '/define', permanent: true },
  { source: '/tags/project-helix', destination: '/news', permanent: true },
  { source: '/tags/18a', destination: '/news', permanent: true },
  { source: '/redbull/chariot-race-missouri-2026', destination: '/redbull', permanent: true },
  { source: '/tags/claude-hacker-puerto-vallarta', destination: '/news', permanent: true },
  { source: '/tags/john-roderick', destination: '/news', permanent: true },
  { source: '/video-games/epic', destination: '/video-games', permanent: true },
  { source: '/tags/sanders-aoc-ai-data-center-moratorium-act-march-2026', destination: '/news', permanent: true },
  { source: '/tags/nycs-ranked-choice-voting-system-faces-scrutiny', destination: '/news', permanent: true },
  { source: '/tags/take-two-ai-team-shake-up-2026', destination: '/news', permanent: true },
  { source: '/video-games/forza-horizon-6/news/pre-launch-511k-steam-presales-alinea-analytics-2026', destination: '/video-games', permanent: true },
  { source: '/tags/gamestop-ps3-xbox-360-wii-u-retro-consoles-march-2026', destination: '/news', permanent: true },
  { source: '/tags/phineas-ferb-skins-april-2026', destination: '/news', permanent: true },
  { source: '/entertainment/marvel/avengers-doomsday-trailer-cinemacon-2026-robert-downey-jr', destination: '/entertainment', permanent: true },
  { source: '/tech/news/softbank-natural-ai-phone-brain-technologies-japan-2026', destination: '/tech', permanent: true },
  { source: '/tags/digital-realty', destination: '/news', permanent: true },
  { source: '/tags/apple-removes-anything-vibe-coding-app-store-2026', destination: '/news', permanent: true },
  { source: '/investigations/rappers/d4vd-arrested-murder-celeste-rivas-hernandez-tesla', destination: '/investigations', permanent: true },
  { source: '/tags/alphabet-raises-32b-in-24-hours-with-rare-100-year-bond', destination: '/news', permanent: true },
  { source: '/tags/blackwell-b300-vs-amd-mi300x-vs-google-tpu-v6-2026-benchmark', destination: '/news', permanent: true },
  { source: '/tags/midas-50m-series-a-rwa-tokenization-liquidity', destination: '/news', permanent: true },
  { source: '/tags/cloudflare-dynamic-workers-open-beta-ai-code-execution-2026', destination: '/news', permanent: true },
  { source: '/trump/musk-pay-tsa-workers-shutdown', destination: '/trump', permanent: true },
  { source: '/tags/ark-raiders', destination: '/news', permanent: true },
  { source: '/tags/vision-pro', destination: '/news', permanent: true },
  { source: '/tags/vast-freshwater-reservoir-found-beneath-great-salt-lake-2026', destination: '/news', permanent: true },
  { source: '/tags/ai-moderation', destination: '/news', permanent: true },
  { source: '/tags/rainbow-six-siege-operation-silent-hunt-y11s1-solid-snake', destination: '/news', permanent: true },
  { source: '/video-games/top-10-anime-games-2026', destination: '/video-games', permanent: true },
  { source: '/tags/jim-keller', destination: '/news', permanent: true },
  { source: '/tags/flash-attention-3-vs-turboquant-vs-paged-kv-cache-llm-optimization', destination: '/news', permanent: true },
  { source: '/tags/chatgpt-brand-apps-realtor-sephora-in-platform-commerce', destination: '/news', permanent: true },
  { source: '/entertainment/movies/street-fighter-movie-2026-trailer-cinemacon-cast-world-warrior', destination: '/entertainment', permanent: true },
  { source: '/lawsuit/california-files-againast-amazon-after-emails-reveiled', destination: '/news', permanent: true },
  { source: '/tech/news/adobe-firefly-ai-assistant-canva-ai-2-agentic-design-2026', destination: '/tech', permanent: true },
  { source: '/tech/stripe/stripe-stablecoins-aws-for-money-payments-2026', destination: '/tech', permanent: true },
  { source: '/video-games/capcom/pragmata-one-million-units-2-days-launch-2026', destination: '/video-games', permanent: true },
  { source: '/video-games/windrose/windrose-222k-concurrent-players-steam-viral-indie-2026', destination: '/video-games', permanent: true },
  { source: '/google/news/iran-cyber-attacks-google-threat-intelligence-march-2026', destination: '/google', permanent: true },
  { source: '/video-games/battlefield-6/news/2026-roadmap-seasons-3-4-5-naval-warfare-back-to-roots', destination: '/video-games', permanent: true },
  { source: '/tags/host-cities-security-funding-frozen-dhs-shutdown', destination: '/news', permanent: true },
  { source: '/tags/ai-development', destination: '/news', permanent: true },
  { source: '/entertainment/news/conan-obrien-hosting-98th-oscars-abc-hulu', destination: '/entertainment', permanent: true },
  { source: '/tags/emx-royalty', destination: '/news', permanent: true },
  { source: '/tags/cristiana-love', destination: '/news', permanent: true },
  { source: '/netflix/news/netflix-q1-2026-earnings-tiktok-feed-ben-affleck-interpositive-reed-hastings', destination: '/netflix', permanent: true },
  { source: '/news/binance-prediction-markets-keyless-wallet-on-chain-probability-trading', destination: '/news', permanent: true },
  { source: '/entertainment/news/project-hail-mary-vr-game-journey-among-the-stars-meta-quest', destination: '/entertainment', permanent: true },
  { source: '/entertainment/news/super-mario-galaxy-movie-371m-global-box-office-opening', destination: '/entertainment', permanent: true },
  { source: '/redbull/news/red-bull-racing-crisis-2026-verstappen-exit-brain-drain', destination: '/redbull', permanent: true },
  { source: '/tech/asml-euv-lithography-profile', destination: '/tech', permanent: true },
  { source: '/tags/rocket-league', destination: '/news', permanent: true },
  { source: '/finance/lead-bank-crypto-infrastructure', destination: '/finance', permanent: true },
  { source: '/finance/news/lead-bank-visa-usdc-solana-crypto-settlement', destination: '/finance', permanent: true },
  { source: '/world-cup/news/world-cup-2026-us-transit-prices-fans-outraged', destination: '/world-cup', permanent: true },
  { source: '/tags/apple', destination: '/news', permanent: true },
  { source: '/tags/automations', destination: '/news', permanent: true },
  { source: '/tags/patch-1.14.0', destination: '/news', permanent: true },
  { source: '/tags/ishowspeed', destination: '/news', permanent: true },
  { source: '/tags/events', destination: '/news', permanent: true },
  { source: '/tags/nintendo-switch-2', destination: '/news', permanent: true },
  { source: '/tech/news/mozilla-thunderbolt-self-hostable-ai-client', destination: '/tech', permanent: true },
  { source: '/tags/creator-economy', destination: '/news', permanent: true },
  { source: '/tags/podcasts', destination: '/news', permanent: true },
  { source: '/video-games/gamestop/news/gamestop-ps3-xbox-360-wii-u-retro-consoles-march-2026', destination: '/video-games', permanent: true },
  { source: '/tags/season-15', destination: '/news', permanent: true },
  { source: '/tags/lindsey-vonn', destination: '/news', permanent: true },
  { source: '/technology/tencent-openclaw-ai-agent-wechat', destination: '/technology', permanent: true },
  { source: '/redbull/run-the-racks-okc-2026', destination: '/redbull', permanent: true },
  { source: '/service/photography-videography-austin-tx', destination: '/service', permanent: true },
  { source: '/define/prediction-market/sdny-prosecutors-insider-trading-prediction-markets-2026', destination: '/define', permanent: true },
  { source: '/tags/dagenham-&-redbridge', destination: '/news', permanent: true },
  { source: '/redbull/dance-your-style-nyc-2026', destination: '/redbull', permanent: true },
  { source: '/redbull/basement-usa-2026', destination: '/redbull', permanent: true },
  { source: '/redbull/wings-for-life-world-run-2026', destination: '/redbull', permanent: true },
  { source: '/tags/alibaba-qwen-3-6-model-preview-responses-api-typescript-sdk-2026', destination: '/news', permanent: true },
  { source: '/elon-musk/news/tesla-terafab-chip-fabrication-launch-march-21-2026', destination: '/elon-musk', permanent: true },
  { source: '/microsoft/news/how-to-accept-usdc-service-business-texas', destination: '/microsoft', permanent: true },
  { source: '/indonesia/news/indonesia-5-5-percent-q1-growth-world-bank-cut', destination: '/news', permanent: true },
  { source: '/trump/news/trump-iran-warning-pakistan-negotiations', destination: '/trump', permanent: true },
  { source: '/influencer/serge-gatari/ai-course-review', destination: '/influencer', permanent: true },
  { source: '/tags/digital-realty-3-25-billion-hyperscale-data-center-fund-2026', destination: '/news', permanent: true },
  { source: '/tags/agentic-ai', destination: '/news', permanent: true },
  { source: '/tags/rainbow-six-siege-y11s1-1-balance-patch-operator-buffs', destination: '/news', permanent: true },
  { source: '/tags/quietbox-2', destination: '/news', permanent: true },
  { source: '/service/surveillance', destination: '/service', permanent: true },
  { source: '/service/asset-collection', destination: '/service', permanent: true },
  { source: '/tags/nvidia-q4-ending-feb-25', destination: '/news', permanent: true },
  { source: '/tags/epic-games-vbucks-shrinkflation-chapter-7-season-2-2026', destination: '/news', permanent: true },
  { source: '/entertainment/news/paramount-skydance-acquires-warner-bros-discovery-110-billion', destination: '/entertainment', permanent: true },
  { source: '/finance/articles/oanda-or-interactive-brokers-forex-trading-usa', destination: '/finance', permanent: true },
  { source: '/news/world-cup-travel-bans-trump-policy', destination: '/news', permanent: true },
  { source: '/microsoft/news/valve-ships-cs2-animation-overhaul-not-cs3-april-2026', destination: '/microsoft', permanent: true },
  { source: '/tags/layoffs', destination: '/news', permanent: true },
  { source: '/video-games/news/rainbow-six-siege-y11s1-1-balance-patch-operator-buffs', destination: '/video-games', permanent: true },
  { source: '/youtube/sidemen/inside-uk', destination: '/youtube', permanent: true },
  { source: '/tags/ai-hardware', destination: '/news', permanent: true },
  { source: '/entertainment/news/marty-supreme-enters-oscar-weekend-nine-nominations-low-odds', destination: '/entertainment', permanent: true },
  { source: '/tags/sitemap', destination: '/news', permanent: true },
  { source: '/tags/alphabet-or-nvidia-here-s-who-i-think-will-win-the-ai-chip-war', destination: '/news', permanent: true },
  { source: '/tags/pegatron-opens-us-factory', destination: '/news', permanent: true },
  { source: '/meta/news/instagram-plus-subscription-test-philippines-japan-mexico-2026', destination: '/meta', permanent: true },
  { source: '/tags/godot-engine', destination: '/news', permanent: true },
  { source: '/finance/news/buffett-dimon-warn-private-credit-risks-threaten-banks', destination: '/finance', permanent: true },
  { source: '/open-ai/news/openai-safety-fellowship-new-yorker-probe', destination: '/open-ai', permanent: true },
  { source: '/tags/strike', destination: '/news', permanent: true },
  { source: '/tags/chloe-kim-historic-three-peat-bid', destination: '/news', permanent: true },
  { source: '/tags/neurophos', destination: '/news', permanent: true },
  { source: '/tags/openai-aws-pentagon-classified-ai-deal-march-2026', destination: '/news', permanent: true },
  { source: '/trump/white-house-app-launch-direct-updates-2026', destination: '/trump', permanent: true },
  { source: '/tags/perplexity', destination: '/news', permanent: true },
  { source: '/video-games/arknights-endfield', destination: '/video-games', permanent: true },
  { source: '/tags/hbomax', destination: '/news', permanent: true },
  { source: '/trump/trump-ice-agents-drop-masks-airports', destination: '/trump', permanent: true },
  { source: '/tags/ask-2026', destination: '/news', permanent: true },
  { source: '/tags/intel-amd-cpu-prices-surge-15-percent-shortage-2026', destination: '/news', permanent: true },
  { source: '/tech/perplexity/news/perplexity-personal-computer-ai-agent-developer-suite-ask-2026', destination: '/tech', permanent: true },
  { source: '/video-games/nintendo/pokemon-pokopia-2-million-copies-4-days-switch-2', destination: '/video-games', permanent: true },
  { source: '/tags/openai', destination: '/news', permanent: true },
  { source: '/tech/news/tenstorrent-tt-quietbox-2-risc-v-ai-workstation-9999', destination: '/tech', permanent: true },
  { source: '/video-games/news/rainbow-six-siege-operation-silent-hunt-y11s1-solid-snake', destination: '/video-games', permanent: true },
  { source: '/winter-olympics/usa/elana-meyers-taylor-bobsled-gold', destination: '/winter-olympics', permanent: true },
  { source: '/tags/epic-games', destination: '/news', permanent: true },
  { source: '/tags/black-lady-blacklives-matter', destination: '/news', permanent: true },
  { source: '/events/gtc-2026/closing-day-3-intel-microsoft-agentic-march-18-2026', destination: '/events', permanent: true },
  { source: '/equipment/dji', destination: '/news', permanent: true },
  { source: '/tags/elemental-royalty', destination: '/news', permanent: true },
  { source: '/tags/amazon-ceo-jassy-ai-eliminate-jobs', destination: '/news', permanent: true },
  { source: '/tags/hedera-vs-solana-for-dapps', destination: '/news', permanent: true },
  { source: '/news/team-usa-womens-hockey-gold-2026', destination: '/news', permanent: true },
  { source: '/tags/usa-sweeps-gold-silver-in-womens-moguls', destination: '/news', permanent: true },
  { source: '/tags/agentic-vision', destination: '/news', permanent: true },
  { source: '/trump/tax-law-corporate-revenue-drop-65-billion', destination: '/trump', permanent: true },
  { source: '/tags/xbox', destination: '/news', permanent: true },
  { source: '/tags/google', destination: '/news', permanent: true },
  { source: '/tags/super-mario', destination: '/news', permanent: true },
  { source: '/tags/donald-trump', destination: '/news', permanent: true },
  { source: '/tags/2025-nissan-z-vs-toyota-gr-supra-comparison', destination: '/news', permanent: true },
  { source: '/tech/news/anthropic-court-filings-disclose-5-billion-in-total-revenue', destination: '/tech', permanent: true },
  { source: '/tags/research', destination: '/news', permanent: true },
  { source: '/tags/switch2', destination: '/news', permanent: true },
  { source: '/tags/alibaba', destination: '/news', permanent: true },
  { source: '/tags/soccer', destination: '/news', permanent: true },
  { source: '/tags/helium-crisis-semiconductor-iran-conflict-2026', destination: '/news', permanent: true },
  { source: '/tags/ceo', destination: '/news', permanent: true },
  { source: '/tags/artemis-ii-launch-lunar-journey-april-2026', destination: '/news', permanent: true },
  { source: '/tags/young-la', destination: '/news', permanent: true },
  { source: '/tags/dell', destination: '/news', permanent: true },
  { source: '/tags/resident-evil', destination: '/news', permanent: true },
  { source: '/tags/saved', destination: '/news', permanent: true },
  { source: '/tags/omega-force', destination: '/news', permanent: true },
  { source: '/tags/environment', destination: '/news', permanent: true },
  { source: '/tech/minimax-maxclaw-openclaw-cloud-agent-clawbot-saas-february-2026', destination: '/tech', permanent: true },
  { source: '/tags/team-usa-womens-hockey-gold-2026', destination: '/news', permanent: true },
  { source: '/tags/time-loop', destination: '/news', permanent: true },
  { source: '/tags/gta6-pre-orders-as-take-two-ausures-sony-microsoft-no-more-delay', destination: '/news', permanent: true },
  { source: '/tags/logan-paul', destination: '/news', permanent: true },
  { source: '/tags/cybersecurity', destination: '/news', permanent: true },
  { source: '/tags/world-cup-travel-bans-trump-policy', destination: '/news', permanent: true },
  { source: '/tags/proof-of-engagement-blockchain-vs-proof-of-authority', destination: '/news', permanent: true },
  { source: '/tags/bryson-dechambeau', destination: '/news', permanent: true },
  { source: '/tags/canada-political-crisis', destination: '/news', permanent: true },
  { source: '/tags/journalism', destination: '/news', permanent: true },
  { source: '/tags/crypto', destination: '/news', permanent: true },
  { source: '/tags/nvidia-groq-inference-processor-gtc-2026', destination: '/news', permanent: true },
  { source: '/tags/trump-executive-directive', destination: '/news', permanent: true },
  { source: '/microsoft/news/microsoft-chevron-7b-texas-power-plant', destination: '/microsoft', permanent: true },
  { source: '/technology/news/midas-50m-series-a-rwa-tokenization-liquidity', destination: '/technology', permanent: true },
  { source: '/open-ai/news/chatgpt-carplay-launch', destination: '/open-ai', permanent: true },
  { source: '/tags/doge', destination: '/news', permanent: true },
  { source: '/tags/nintendo', destination: '/news', permanent: true },
  { source: '/tags/paramount-skydance', destination: '/news', permanent: true },
  { source: '/tags/ddos', destination: '/news', permanent: true },
  { source: '/events/davos/all-in-podcast', destination: '/events', permanent: true },
  { source: '/winter-olympics/france/biathlon-relay-gold-perrot-2026', destination: '/winter-olympics', permanent: true },
  { source: '/tags/lng', destination: '/news', permanent: true },
  { source: '/events/davos/all-in-podcast/david-sacks', destination: '/events', permanent: true },
  { source: '/tags/gran-turismo', destination: '/news', permanent: true },
  { source: '/winter-olympics/lindsey-vonn/near-amputation-fasciotomy', destination: '/winter-olympics', permanent: true },
  { source: '/netflix/news/netflix-acquires-ben-affleck-interpositive-ai-startup', destination: '/netflix', permanent: true },
  { source: '/microsoft/xbox/asha-sharma', destination: '/microsoft', permanent: true },
  { source: '/video-games/racing/polyphony-gran-turismo', destination: '/video-games', permanent: true },
  { source: '/video-games/news/my-hero-ultra-rumble-season-15-review', destination: '/video-games', permanent: true },
  { source: '/video-games/news/gta6-pre-orders-as-take-two-ausures-sony-microsoft-no-more-delay', destination: '/video-games', permanent: true },
  { source: '/winter-olympics/usa-sweeps-gold-silver-in-womens-moguls', destination: '/winter-olympics', permanent: true },
  { source: '/tags/diamond-gym', destination: '/news', permanent: true },
  { source: '/video-games/mha/ultra-rumble/season-15/strike-overhaul', destination: '/video-games', permanent: true },
  { source: '/winter-olympics/norway/oftebro-second-nordic-combined-gold', destination: '/winter-olympics', permanent: true },
  { source: '/winter-olympics/news/malinin-fair-play-award-milano-cortina-2026-wrap-up', destination: '/winter-olympics', permanent: true },
  { source: '/events/news/claude-hacker-puerto-vallarta', destination: '/events', permanent: true },
  { source: '/redbull/showrun-san-francisco-2026', destination: '/redbull', permanent: true },
  { source: '/redbull/bc-one-cypher-denver-2026', destination: '/redbull', permanent: true },
  { source: '/winter-olympics/usa/ilia-malinin', destination: '/winter-olympics', permanent: true },
  { source: '/entertainment/news/prophet-ebo-noah-s-flood-prophecy', destination: '/entertainment', permanent: true },
  { source: '/tags/ai-chips', destination: '/news', permanent: true },
  { source: '/tags/new-balance', destination: '/news', permanent: true },
  { source: '/tags/mining', destination: '/news', permanent: true },
  { source: '/tags/innersloth', destination: '/news', permanent: true },
  { source: '/tags/nick-shirley-drops-second-part-of-fraud-investigation', destination: '/news', permanent: true },
  { source: '/artists/central-cee', destination: '/artists', permanent: true },
  { source: '/equipment/hasselblad', destination: '/news', permanent: true },
  { source: '/youtube/sidemen/inside-uk/season3/ratings-review-winner', destination: '/youtube', permanent: true },
  { source: '/tags/irgc', destination: '/news', permanent: true },
  { source: '/tags/tesla-terafab-chip-fabrication-launch-march-21-2026', destination: '/news', permanent: true },
  { source: '/entertainment/news/super-mario-galaxy-movie-kyoto-premiere-2026', destination: '/entertainment', permanent: true },
  { source: '/finance/private-credit-redemption-crisis-blackstone-blackrock-blue-owl-2026', destination: '/finance', permanent: true },
  { source: '/tags/chippo-grimes', destination: '/news', permanent: true },
  { source: '/tags/open-source-ai', destination: '/news', permanent: true },
  { source: '/finance/articles/nasdaq-proposed-24-7-trading', destination: '/finance', permanent: true },
  { source: '/tags/slovenia', destination: '/news', permanent: true },
  { source: '/nvidia/news/indie-devs-dlss5-boycott-new-blood-interactive', destination: '/nvidia', permanent: true },
  { source: '/video-games/star-wars/star-wars-zero-company', destination: '/video-games', permanent: true },
  { source: '/technology/news/kaiser-permanente-ufcw-contract-ai-protections-2026', destination: '/technology', permanent: true },
  { source: '/tags/tyler-lucas-wins-kalshi-priced-in', destination: '/news', permanent: true },
  { source: '/tags/ilhan-omar', destination: '/news', permanent: true },
  { source: '/saas/hashicorp', destination: '/saas', permanent: true },
  { source: '/tags/housing-market', destination: '/news', permanent: true },
  { source: '/tags/render-vs-vercel-for-free-start-up-app-deployment', destination: '/news', permanent: true },
  { source: '/tags/ai-sovereignty-shift', destination: '/news', permanent: true },
  { source: '/tags/yamanaka-factors-reverse-cellular-aging-markers', destination: '/news', permanent: true },
  { source: '/tags/team-usa', destination: '/news', permanent: true },
  { source: '/tags/horror', destination: '/news', permanent: true },
  { source: '/tech/federal-agencies-grok-safety-concerns-pentagon-classified-approval-2026', destination: '/tech', permanent: true },
  { source: '/tags/bank-of-america', destination: '/news', permanent: true },
  { source: '/blog/open-ai-altman-government-oversight-pentagon-deal', destination: '/news', permanent: true },
  { source: '/tags/clair-obscur', destination: '/news', permanent: true },
  { source: '/tags/espn', destination: '/news', permanent: true },
  { source: '/tags/elon-musk', destination: '/news', permanent: true },
  { source: '/tags/ksi', destination: '/news', permanent: true },
  { source: '/tags/enterprise-ai', destination: '/news', permanent: true },
  { source: '/tech/dell/dell-pro-max-gb300-grace-blackwell-ultra-desktop-gtc-2026', destination: '/tech', permanent: true },
  { source: '/winter-olympics/italy/luca-spechenhauser', destination: '/winter-olympics', permanent: true },
  { source: '/google/google-research-releases-turboquant', destination: '/google', permanent: true },
  { source: '/tags/jensenhuang-ai-agent-will-boost-enterprise-software-value', destination: '/news', permanent: true },
  { source: '/trump/trump-auto-tariffs-25-percent-april-3', destination: '/trump', permanent: true },
  { source: '/tags/codex', destination: '/news', permanent: true },
  { source: '/tags/ferrari', destination: '/news', permanent: true },
  { source: '/blog/winter-olympics-news-malinin-fair-play-award-milano-cortina-2026-wrap-up', destination: '/news', permanent: true },
  { source: '/news/texas/asml-hutto-semiconductor', destination: '/news', permanent: true },
  { source: '/tags/austin', destination: '/news', permanent: true },
  { source: '/blog/austin-waymo-city-council-bufords-ambulance-obstruction-2026', destination: '/news', permanent: true },
  { source: '/tags/season3', destination: '/news', permanent: true },
  { source: '/blog/video-games-news-rockstar-gta6-psn-profile-exploit', destination: '/news', permanent: true },
  { source: '/blog/video-games-nintendo-mar10-day-2026-40th-anniversary-super-mario', destination: '/news', permanent: true },
  { source: '/blog/copyright-elemental-atlus-royalties', destination: '/news', permanent: true },
  { source: '/youtube/chicos-toxicos', destination: '/youtube', permanent: true },
  { source: '/winter-olympics/china/eileen-gu', destination: '/winter-olympics', permanent: true },
  { source: '/disney/news/disney-execs-pleased-avengers-doomsday-mcu-box-office-slump', destination: '/disney', permanent: true },
  { source: '/tags/gaming-rankings', destination: '/news', permanent: true },
  { source: '/tags/missing-persons', destination: '/news', permanent: true },
  { source: '/youtube/sidemen/inside-uk/season3', destination: '/youtube', permanent: true },
  { source: '/tags/blighted-precipice', destination: '/news', permanent: true },
  { source: '/tags/first-winter-olympic-medal-figure-skating', destination: '/news', permanent: true },
  { source: '/tags/who-owns-the-ocean-floor', destination: '/news', permanent: true },
  { source: '/cloudflare/news/dynamic-workers-open-beta-ai-code-execution-2026', destination: '/cloudflare', permanent: true },
  { source: '/social/meta/news/meta-ray-ban-display-glasses-eu-blocked-battery-regulation-2026', destination: '/social', permanent: true },
  { source: '/saas/news/render-vs-vercel-for-free-start-up-app-deployment', destination: '/saas', permanent: true },
  { source: '/tags/among-us', destination: '/news', permanent: true },
  { source: '/tags/juno-ice-shell-18-miles-thick', destination: '/news', permanent: true },
  { source: '/blog/nvidia-news-nvidia-blackwell-b300-data-center-demand-surge-2026', destination: '/news', permanent: true },
  { source: '/blog/google-google-research-releases-turboquant', destination: '/news', permanent: true },
  { source: '/news/texas/austin-tech-hub-decline', destination: '/news', permanent: true },
  { source: '/earth/news/japan-chikyu-deep-sea-rare-earth-extraction', destination: '/news', permanent: true },
  { source: '/tags/claude', destination: '/news', permanent: true },
  { source: '/winter-olympics/usa/alysa-liu', destination: '/winter-olympics', permanent: true },
  { source: '/entertainment/beastgames/season-2', destination: '/entertainment', permanent: true },
  { source: '/tags/vince-vaughn', destination: '/news', permanent: true },
  { source: '/tags/milan-cortina-2026', destination: '/news', permanent: true },
  { source: '/youtube/thefellas', destination: '/youtube', permanent: true },
  { source: '/service/infidelity', destination: '/service', permanent: true },
  { source: '/tags/us-politics', destination: '/news', permanent: true },
  { source: '/tags/team', destination: '/news', permanent: true },
  { source: '/tags/fashion', destination: '/news', permanent: true },
  { source: '/tags/behzinga', destination: '/news', permanent: true },
  { source: '/blog/technology-stablecoins-paypal-pyusd-70-markets-global-expansion-march-2026', destination: '/news', permanent: true },
  { source: '/blog/california-california-highway-expansion-2026-state-transportation-improvement-program', destination: '/news', permanent: true },
  { source: '/tags/critical-minerals', destination: '/news', permanent: true },
  { source: '/tags/legal', destination: '/news', permanent: true },
  { source: '/blog/amazon-news-amazon-acquires-fauna-robotics-sprout-humanoid', destination: '/news', permanent: true },
  { source: '/technology/wordpress-ai-agents-write-publish-content-mcp-2026', destination: '/technology', permanent: true },
  { source: '/blog/trump-trump-ice-agents-drop-masks-airports', destination: '/news', permanent: true },
  { source: '/tags/patch-notes', destination: '/news', permanent: true },
  { source: '/tags/pending-home-sales', destination: '/news', permanent: true },
  { source: '/blog/trump-musk-pay-tsa-workers-shutdown', destination: '/news', permanent: true },
  { source: '/blog/events-gdc-2026', destination: '/news', permanent: true },
  { source: '/blog/microsoft-xbox', destination: '/news', permanent: true },
  { source: '/blog/bio-hacking', destination: '/news', permanent: true },
  { source: '/blog/rocket-league', destination: '/news', permanent: true },
  { source: '/blog/microsoft', destination: '/news', permanent: true },
  { source: '/tags/genius-act', destination: '/news', permanent: true },
  { source: '/tags/contact', destination: '/news', permanent: true },
  { source: '/tags/logan-paul-sells-pokemon-card-16-million', destination: '/news', permanent: true },
  { source: '/tags/the-2026-sovereign-squeeze-ai-nuclear-age', destination: '/news', permanent: true },
  { source: '/tags/forza-horizon-6', destination: '/news', permanent: true },
  { source: '/tags/enterprise', destination: '/news', permanent: true },
  { source: '/tags/hetzner-cloud-vs-digitalocean', destination: '/news', permanent: true },
  { source: '/tags/console-footage-pushback', destination: '/news', permanent: true },
  { source: '/tags/how-do-prediction-markets-work', destination: '/news', permanent: true },
  { source: '/disney/news/incoming-ceo-floats-premiering-films-in-fortnite', destination: '/disney', permanent: true },
  { source: '/tags/blue-owl-halts-fund-redemptions', destination: '/news', permanent: true },
  { source: '/tags/marathon', destination: '/news', permanent: true },
  { source: '/winter-olympics/lindsey-vonn-training-downhill', destination: '/winter-olympics', permanent: true },
  { source: '/tags/prophet-ebo-noah-s-flood-prophecy', destination: '/news', permanent: true },
  { source: '/tags/swarm-engine', destination: '/news', permanent: true },
  { source: '/tags/virtual-production', destination: '/news', permanent: true },
  { source: '/tags/alibaba-ai-agent-mined-crypto-during-training', destination: '/news', permanent: true },
  { source: '/tags/digital-director', destination: '/news', permanent: true },
  { source: '/tags/john-carpenter', destination: '/news', permanent: true },
  { source: '/tags/eileen-gu', destination: '/news', permanent: true },
  { source: '/tags/index', destination: '/news', permanent: true },
  { source: '/tags/milano-cortina-2026', destination: '/news', permanent: true },
  { source: '/winter-olympics/italy/speedskating-team-pursuit-gold-2026', destination: '/winter-olympics', permanent: true },
  { source: '/tags/microsoft', destination: '/news', permanent: true },
  { source: '/tags/fired', destination: '/news', permanent: true },
  { source: '/tags/lawsuit', destination: '/news', permanent: true },
  { source: '/tags/generative-ai', destination: '/news', permanent: true },
  { source: '/tags/icvfx', destination: '/news', permanent: true },
  { source: '/tags/steam-launch-record-267k-concurrent-players', destination: '/news', permanent: true },
  { source: '/microsoft/news/yamanaka-factors-reverse-cellular-aging-markers', destination: '/microsoft', permanent: true },
  { source: '/tags/life-biosciences-fda-clearance-er-100-epigenetic-reprogramming-optic-neuropathy-2026', destination: '/news', permanent: true },
  { source: '/tags/unreal-engine', destination: '/news', permanent: true },
  { source: '/tags/aws-uae-data-center-fire-iran-strikes', destination: '/news', permanent: true },
  { source: '/tags/incoming-ceo-floats-premiering-films-in-fortnite', destination: '/news', permanent: true },
  { source: '/finance/articles/the-trillion-dollar-treasure-trove-in-the-deep-sea', destination: '/finance', permanent: true },
  { source: '/tags/bellwright', destination: '/news', permanent: true },
  { source: '/tags/release-date-holdoff', destination: '/news', permanent: true },
  { source: '/tags/bungie', destination: '/news', permanent: true },
  { source: '/influencer/bryson-dechambeau/kalshi', destination: '/influencer', permanent: true },
  { source: '/tags/kotor-remake-saber-confirmed-still-in-development', destination: '/news', permanent: true },
  { source: '/events/davos/all-in-podcast/jason', destination: '/events', permanent: true },
  { source: '/news/2025/jerome-powell-federal-reserve-headquarters-renovation', destination: '/news', permanent: true },
  { source: '/tags/wishlists', destination: '/news', permanent: true },
  { source: '/winter-olympics/final-ceremony', destination: '/winter-olympics', permanent: true },
  { source: '/tags/arr', destination: '/news', permanent: true },
  { source: '/tags/norway', destination: '/news', permanent: true },
  { source: '/tags/statistical-edge-permutation-testing-trading', destination: '/news', permanent: true },
  { source: '/tags/mastercard', destination: '/news', permanent: true },
  { source: '/finance/articles/starlink-economic-analysis', destination: '/finance', permanent: true },
  { source: '/microsoft/news/nvidia-groq-inference-processor-gtc-2026', destination: '/microsoft', permanent: true },
  { source: '/tags/mars', destination: '/news', permanent: true },
  { source: '/tags/china', destination: '/news', permanent: true },
  { source: '/video-games/valve-corporation/court-ruling-private-companies-can-enforce-patent-troll-prevention-act', destination: '/video-games', permanent: true },
  { source: '/tags/authors', destination: '/news', permanent: true },
  { source: '/tags/foundry', destination: '/news', permanent: true },
  { source: '/tags/search', destination: '/news', permanent: true },
  { source: '/winter-olympics/swiss-skier-von-allmen-wins-third-gold', destination: '/winter-olympics', permanent: true },
  { source: '/tags/virtual-boy', destination: '/news', permanent: true },
  { source: '/tags/drake', destination: '/news', permanent: true },
  { source: '/tags/private-investigations', destination: '/news', permanent: true },
  { source: '/tags/reference', destination: '/news', permanent: true },
  { source: '/tags/mandiant', destination: '/news', permanent: true },
  { source: '/tags/stock-market', destination: '/news', permanent: true },
  { source: '/tags/comet-ai-web-browser-vs-atlas-by-chatgpt', destination: '/news', permanent: true },
  { source: '/tags/nestjs-vs-nextjs-express', destination: '/news', permanent: true },
  { source: '/tags/france', destination: '/news', permanent: true },
  { source: '/tags/getfreetogether', destination: '/news', permanent: true },
  { source: '/tags/difference-between-http-and-rest-api-servers', destination: '/news', permanent: true },
  { source: '/tags/health', destination: '/news', permanent: true },
  { source: '/tags/copilot', destination: '/news', permanent: true },
  { source: '/tags/my-hero-academia', destination: '/news', permanent: true },
  { source: '/tags/apple-intelligence', destination: '/news', permanent: true },
  { source: '/non-degree-studies-at-university-of-texas-austin', destination: '/college', permanent: true },
  { source: '/tags/x-twitter', destination: '/news', permanent: true },
  { source: '/tags/co-op', destination: '/news', permanent: true },
  { source: '/tags/tags', destination: '/news', permanent: true },
  { source: '/tags/prime', destination: '/news', permanent: true },
  { source: '/tags/apple-march-2026-products-macbook-iphone-17e-ipad-air-m5', destination: '/news', permanent: true },
  { source: '/tags/alphabet', destination: '/news', permanent: true },
  { source: '/tags/europa', destination: '/news', permanent: true },
  { source: '/tags/don-toliver', destination: '/news', permanent: true },
  { source: '/tags/help', destination: '/news', permanent: true },
  { source: '/tags/zerkaa', destination: '/news', permanent: true },
  { source: '/tags/canada', destination: '/news', permanent: true },
  { source: '/tags/comedy', destination: '/news', permanent: true },
  { source: '/tags/andy-carroll', destination: '/news', permanent: true },
  { source: '/tags/education', destination: '/news', permanent: true },
  { source: '/tags/trump-epa-move-green-paradox', destination: '/news', permanent: true },
  { source: '/tags/stefano-domenicali', destination: '/news', permanent: true },
  { source: '/tags/mac-mini-houston-tx', destination: '/news', permanent: true },
  { source: '/tags/ngo', destination: '/news', permanent: true },
  { source: '/saas/news/introducing-bitchat-jack-dorseys-game-changing-bluetooth-mesh-messaging-app', destination: '/saas', permanent: true },
  { source: '/service/fact-finding-and-evidence-collection', destination: '/service', permanent: true },
  { source: '/google/agentic-vision', destination: '/google', permanent: true },
  { source: '/podcasts/joe-rogan', destination: '/news', permanent: true },
  { source: '/service/press-release', destination: '/service', permanent: true },
  { source: '/winter-olympics/lindsey-vonn', destination: '/winter-olympics', permanent: true },
  { source: '/finance/articles/the-2026-sovereign-squeeze-ai-nuclear-age', destination: '/finance', permanent: true },
  { source: '/tags/newyork', destination: '/news', permanent: true },
  { source: '/finance/articles/how-the-cme-rules-the-world', destination: '/finance', permanent: true },
  { source: '/james-cameron', destination: '/entertainment', permanent: true },
  { source: '/social/meta', destination: '/social', permanent: true },
  { source: '/oanda-or-interactive-brokers-forex-trading-usa', destination: '/finance', permanent: true },
  { source: '/coding/nestjs-vs-nextjs-vs-express', destination: '/news', permanent: true },
  { source: '/mha', destination: '/video-games', permanent: true },
  { source: '/james-cameron/avatar-fire-and-ash', destination: '/news', permanent: true },
  { source: '/infidelity', destination: '/service/infidelity', permanent: true },
  { source: '/surveillance', destination: '/service/surveillance', permanent: true },
  { source: '/contactus', destination: '/', permanent: true },
      // AUTO: broader wildcards replacing invalid prefix-:path* patterns
      { source: '/google/news/:path*', destination: '/google', permanent: true },
      { source: '/microsoft/news/:path*', destination: '/microsoft', permanent: true },
      { source: '/nasa/news/:path*', destination: '/nasa', permanent: true },
      { source: '/news/:path+', destination: '/news', permanent: true },
      { source: '/nvidia/news/:path*', destination: '/nvidia', permanent: true },
      { source: '/open-ai/:path+', destination: '/open-ai', permanent: true },
      { source: '/redbull/:path+', destination: '/redbull', permanent: true },
      { source: '/saas/news/:path*', destination: '/saas', permanent: true },
      { source: '/tech/:path+', destination: '/tech', permanent: true },
      { source: '/tech/news/:path*', destination: '/tech', permanent: true },
      { source: '/tech/perplexity/news/:path*', destination: '/tech', permanent: true },
      { source: '/technology/:path+', destination: '/technology', permanent: true },
      { source: '/trump/:path+', destination: '/trump', permanent: true },
      { source: '/video-games/:path+', destination: '/video-games', permanent: true },
      { source: '/video-games/nintendo/:path*', destination: '/video-games', permanent: true },

];
